### ISSUE TITLE
signalr.exe ghp /url:<URL>

### ISSUE THREAD

**Issue by gustavo-armenta** [SignalR/SignalR#1295]
Probably we should print the URL that was not found, so the developer can realize the website has no hubs. In this sample, the URL not found is http://localhost/signalr/hubs

<b>signalr ghp /url:http://localhost/</b>
SignalR Utility Version: 1.0.0.0

```
Error: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at Microsoft.AspNet.SignalR.Utils.GenerateHubProxyCommand.OutputHubsFromUrl(String url, String outputPath, Boolean absolute) in d:\SignalR\release\src\Microsoft.AspNet.SignalR.Utils\Commands\GenerateHubProxyCommand.cs:line 133
   at Microsoft.AspNet.SignalR.Utils.GenerateHubProxyCommand.Execute(String[] args) in d:\SignalR\release\src\Microsoft.AspNet.SignalR.Utils\Commands\GenerateHubProxyCommand.cs:line 60
   at Microsoft.AspNet.SignalR.Utils.Program.Main(String[] args) in d:\SignalR\release\src\Microsoft.AspNet.SignalR.Utils\Program.cs:line 43
```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
