### ISSUE TITLE
IIS express crashed

### ISSUE THREAD

**Issue by erymuzuan** [SignalR/SignalR#1395]
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNet.SignalR.Messaging.DefaultSubscription.PerformWork(List`1 items, Int32& totalCount, Object& state)
   at Microsoft.AspNet.SignalR.Messaging.Subscription.WorkImpl(TaskCompletionSource`1 taskCompletionSource)
   at Microsoft.AspNet.SignalR.Messaging.Subscription.Work()
   at Microsoft.AspNet.SignalR.Messaging.MessageBroker.PumpImpl(TaskCompletionSource`1 taskCompletionSource, ISubscription subscri
ption)
   at Microsoft.AspNet.SignalR.Messaging.MessageBroker.PumpAsync()
   at Microsoft.AspNet.SignalR.Messaging.MessageBroker.ProcessWork(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boo
lean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean pre
serveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
