### ISSUE TITLE
OWIN: Server cannot append header after HTTP headers have been sent

### ISSUE THREAD

**Issue by MosheL** [SignalR/SignalR#1524]
When using serverSentEvents or ForeverFrame, and with send/abort commands sometimes I can see this error:

Someone in Owin.Host try to set headers after response was sent. also as I know  send and abort do not need to disable buffering as they just sent as a normal HTTP request.

``` VB.net
Call Stack:
•[Server cannot append header after HTTP headers have been sent.]
at System.Web.HttpResponse.AppendHeader(String name, String value)
at Microsoft.Owin.Host.SystemWeb.OwinCallContext.DisableResponseBuffering()
at Microsoft.AspNet.SignalR.Owin.CallHandler.Invoke(IDictionary`2 environment)
at Microsoft.Owin.Host.SystemWeb.OwinCallContext.Execute()
at Microsoft.Owin.Host.SystemWeb.OwinHttpHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object extraData)
•[Exception has been thrown by the target of an invocation.]
at Microsoft.Owin.Host.SystemWeb.CallContextAsyncResult.End(IAsyncResult result)
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

IIS 7.5@ Windows  2008, SignalR 1.0.0rc2 from nuget.

**Comment by anilsingh581** [comment]
Can help me, I am getting an  error on line
((IController)controller).Execute(new RequestContext(new HttpContextWrapper(System.Web.HttpContext.Current), routeData));

error: 
An exception of type 'System.Web.HttpException' occurred in System.Web.Mvc.dll but was not handled in user code

Additional information: Server cannot set status after HTTP headers have been sent.

Thank you!!
http://www.code-sample.com/

**Comment by bchilukuri** [comment]
Remove Response.Flush() if you have any..

**Comment by MosheL** [comment]
I do not use Response.Flush. this is the first option I was checked.
