### ISSUE TITLE
JS client event is raised more times than it should be for one calling from hub when in client multiple hub proxies register

### ISSUE THREAD

**Issue by Xiaohongt** [SignalR/SignalR#1540]
e.g. in below JS test, it only calls one time echoHub.server.echoCallback("hello"), but echoHub.client.echo event is raised 3 times for the same message.

Note, it is not regression.

``` javascript
QUnit.module("Hub Messages Send and Receive Facts");

testUtilities.runWithAllTransports(function (transport) {

    QUnit.asyncTimeoutTest(transport + ": for multiple Hubs in one hub connection.", testUtilities.defaultTestTimeout, function (end, assert, testName) {
        var connection = testUtilities.createHubConnection(),
            echoHub = connection.createHubProxies().echoHub,
            noAuthHub = connection.createHubProxies().noAuthHub,
            demo = connection.createHubProxies().demo,
            messageCount = 0;

        echoHub.client.echo = function (value) {
            if (value === "hello") {
                messageCount++;
                if (messageCount == 1) {
                    assert.ok(true, "Successful received message for echoHub ");
                    //give a chance to verify that if receive message more times than expected
                    window.setTimeout(end, 1000);
                }

                if (messageCount > 1) {
                    assert.ok(false, "Failed received more message unexpectedly " + value);
                };
            }               
        };

        connection.start({ transport: transport }).done(function () {
            assert.ok(true, "Connected");
            echoHub.server.echoCallback("hello");
        }).fail(function (reason) {
            assert.ok(false, "Failed to initiate SignalR connection");
            end();
        });

        // Cleanup
        return function () {
            connection.stop();
        };
    });

});
```

in EchoHub class:

``` csharp
        public Task EchoCallback(string message)
        {
            return Clients.Caller.echo(message);
        }
```

Test results like:
1.  Connected
2.  Successful received message for echoHub 
3.  Failed received more message unexpectedly hello
Source:        at ok (http://localhost:41301/Scripts/qunit.extensions.js:57:33)
   at echo (http://localhost:41301/Tests/FunctionalTests/xiaota/HubSendReceiveFacts.js:23:21)
   at Anonymous function (http://localhost:41301/signalr/hubs:26:13)
   at Anonymous function (http://localhost:41301/Scripts/jquery.signalR.js:1754:17)
   at handle (http://localhost:41301/Scripts/jquery-1.6.4.js:3001:5)
   at eventHandle (http://localhost:41301/Scripts/jquery-1.6.4.js:2634:5)
   at trigger (http://localhost:41301/Scripts/jquery-1.6.4.js:2929:5)
   at triggerHandler (http://localhost:41301/Scripts/jquery-1.6.4.js:3543:4)
4.  Failed received more message unexpectedly hello
Source:        at ok (http://localhost:41301/Scripts/qunit.extensions.js:57:33)
   at echo (http://localhost:41301/Tests/FunctionalTests/xiaota/HubSendReceiveFacts.js:23:21)
   at Anonymous function (http://localhost:41301/signalr/hubs:26:13)
   at Anonymous function (http://localhost:41301/Scripts/jquery.signalR.js:1754:17)
   at handle (http://localhost:41301/Scripts/jquery-1.6.4.js:3001:5)
   at eventHandle (http://localhost:41301/Scripts/jquery-1.6.4.js:2634:5)
   at trigger (http://localhost:41301/Scripts/jquery-1.6.4.js:2929:5)
   at triggerHandler (http://localhost:41301/Scripts/jquery-1.6.4.js:3543:4)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
