### ISSUE TITLE
[LP] MultipleHubs test failed with WebException - 503 Server Unavailable

### ISSUE THREAD

**Issue by jcondex** [SignalR/SignalR#1719]
Our [LP]MultipleHubs scenario failed with the below exception.  This test passed using WebSocketTransport.

```
StressTestLogger Critical: 137 : [18:38:10] System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at Microsoft.AspNet.SignalR.Client.Http.HttpHelper.<>c__DisplayClass2.<GetHttpResponseAsync>b__0(IAsyncResult ar) in c:\Users\jconde\Documents\GitHub\SignalR\src\Microsoft.AspNet.SignalR.Client\Http\HttpHelper.cs:line 22
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at Microsoft.AspNet.SignalR.Client.Http.HttpHelper.<>c__DisplayClass2.<GetHttpResponseAsync>b__0(IAsyncResult ar) in c:\Users\jconde\Documents\GitHub\SignalR\src\Microsoft.AspNet.SignalR.Client\Http\HttpHelper.cs:line 22
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---
```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
