### ISSUE TITLE
Addition of Redis backplane causes "The queue is closed" exceptions

### ISSUE THREAD

**Issue by dbelcham** [SignalR/SignalR#1883]
- Downloaded, compiled and installed Redis from here: https://github.com/MSOpenTech/redis
- Have it running and verified with ping/pong.
- Cloned a local copy of the master at SHA 8d929cf
- Modify \Samples\Microsoft.AspNet.SignalR.Hosting.AspNet.Samples so that Global.asax.cs has the following code as the first line in Application_Start:

```
GlobalHost.DependencyResolver.UseRedis("localhost", 6379, "mypassword", "myapplication");
```
- Run application, select Chat demo and attempt "/nick asdf". Following error is thrown:

"The queue is closed"
       at Microsoft.AspNet.SignalR.Messaging.ScaleoutTaskQueue.Enqueue(Func`2 send, Object state) in c:\working\SignalR\src\Microsoft.AspNet.SignalR.Core\Messaging\ScaleoutTaskQueue.cs:line 69
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutStreamManager.Send(Int32 streamIndex, IList`1 messages) in c:\working\SignalR\src\Microsoft.AspNet.SignalR.Core\Messaging\ScaleoutStreamManager.cs:line 61
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.Send(IList`1 messages) in c:\working\SignalR\src\Microsoft.AspNet.SignalR.Core\Messaging\ScaleoutMessageBus.cs:line 94
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.Publish(Message message) in c:\working\SignalR\src\Microsoft.AspNet.SignalR.Core\Messaging\ScaleoutMessageBus.cs:line 208
   at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message) in c:\working\SignalR\src\Microsoft.AspNet.SignalR.Core\Infrastructure\Connection.cs:line 123
   at Microsoft.AspNet.SignalR.Transports.TransportConnectionExtensions.SendCommand(ITransportConnection connection, String connectionId, CommandType commandType) in c:\working\SignalR\src\Microsoft.AspNet.SignalR.Core\Transports\TransportConnectionExtensions.cs:line 31
   at Microsoft.AspNet.SignalR.Transports.TransportConnectionExtensions.Abort(ITransportConnection connection, String connectionId) in 
c:\working\SignalR\src\Microsoft.AspNet.SignalR.Core\Transports\TransportConnectionExtensions.cs:line 18
   at Microsoft.AspNet.SignalR.Transports.LongPollingTransport.ProcessRequest(ITransportConnection connection) in c:\working\SignalR\src\Microsoft.AspNet.SignalR.Core\Transports\LongPollingTransport.cs:line 135
   at Microsoft.AspNet.SignalR.PersistentConnection.ProcessRequest(HostContext context) in c:\working\SignalR\src\Microsoft.AspNet.SignalR.Core\PersistentConnection.cs:line 227
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.ProcessRequest(HostContext context) in c:\working\SignalR\src\Microsoft.AspNet.SignalR.Core\Hubs\HubDispatcher.cs:line 243
   at Microsoft.AspNet.SignalR.Owin.CallHandler.Invoke(IDictionary`2 environment) in c:\working\SignalR\src\Microsoft.AspNet.SignalR.Owin\Handlers\CallHandler.cs:line 74
   at Microsoft.AspNet.SignalR.Owin.Handlers.HubDispatcherHandler.Invoke(IDictionary`2 environment) in c:\working\SignalR\src\Microsoft.AspNet.SignalR.Owin\Handlers\HubDispatcherHandler.cs:line 37
   at Microsoft.AspNet.SignalR.Samples.RouteConfig.<>c__DisplayClass5.<AuthMiddleware>b__3(IDictionary`2 env) in c:\working\SignalR\samples\Microsoft.AspNet.SignalR.Hosting.AspNet.Samples\App_Start\RouteConfig.cs:line 46
   at Microsoft.Owin.Host.SystemWeb.OwinCallContext.Execute()

**Comment by LastTribunal** [comment]
I gotta say, Sig'r and Redis are a match made in heaven, zero config!
