### ISSUE TITLE
The WebSocket instance cannot be used for communication because it has been transitioned into an invalid state.

### ISSUE THREAD

**Issue by esp0** [SignalR/SignalR#2440]
We are using Microsoft.AspNet.SignalR.Core.2.0.0-beta2 from nuget and running the site in an azure web worker (only 1 instance for now, so no backplane/scaleup).

When a client computer running latest Firefox (or IE) goes to sleep for 60 seconds and then wakes up again, the following error is logged:

```
SignalR exception thrown by Task: System.AggregateException: One or more errors occurred. ---> System.Net.WebSockets.WebSocketException: The WebSocket instance cannot be used for communication because it has been transitioned into an invalid state.
  at System.Web.WebSockets.AspNetWebSocket.CloseOutputAsyncImpl(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken, Boolean performValidation)
  at System.Web.WebSockets.AspNetWebSocket.CloseOutputAsync(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken)
  at Microsoft.AspNet.SignalR.WebSockets.WebSocketHandler.<CloseAsync>b__2(Object state)
  at Microsoft.AspNet.SignalR.Infrastructure.TaskQueue.<Enqueue>b__1(Func`2 next, Object nextState)
  at Microsoft.AspNet.SignalR.TaskAsyncHelper.FromMethod[T1,T2](Func`3 func, T1 arg1, T2 arg2)

```

I found a simular issue #1846, but that was solved 4 months ago so maybe this is something different? I am not sure, but I think I am loosing some connect/disconnect events on the server because of this.

**Comment by MhAlan** [comment]
Is this thing SignalR is dead or what?
