### ISSUE TITLE
System.ArgumentNullException: Value cannot be null in TransportHelper.GetReceiveQueryString

### ISSUE THREAD

**Issue by corneliutusnea** [SignalR/SignalR#2813]
Getting this exception with SignalR .Net clients using LongPolling.
Can't really reproduce it in my test environment but I can see it coming through logs randomly from various clients.

It always seems to happen few seconds after  a disconnect/reconnect procedure:

Exception:

This is what I see in my logs:
<Debug> -- 1/12/2014 7:31:14 PM -- T(57): ConnectionState Changed: Reconnecting
<Debug> -- 1/12/2014 7:31:14 PM -- T(57): ConnectionState Changed: Reconnecting
<Debug> -- 1/12/2014 7:32:14 PM -- T(34): ConnectionState Changed: Disconnected

[this is from the Closed event handler]
<Error> -- 1/12/2014 7:32:14 PM -- T(34): Connection dropped - restarting the connection...

(this is us starting a new Connection 30 seconds later)

<Debug> -- 1/12/2014 7:32:46 PM -- T(34): ConnectionState Changed: Connecting
<Debug> -- 1/12/2014 7:32:48 PM -- T(3): ConnectionState Changed: Connected
<Debug> -- 1/12/2014 7:32:48 PM -- T(3): ServerChannel: Connected to server
<Error> -- 1/12/2014 7:32:53 PM -- T(2): UnobservedTaskException:

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: stringToEscape
   at System.Uri.EscapeDataString(String stringToEscape)
   at Microsoft.AspNet.SignalR.Client.Transports.TransportHelper.GetReceiveQueryString(IConnection connection, String connectionData, String transport)
   at Microsoft.AspNet.SignalR.Client.Transports.LongPollingTransport.<>c__DisplayClassd.<PollingSetup>b__5()
   at Microsoft.AspNet.SignalR.Client.Transports.PollingRequestHandler.Poll()
   at Microsoft.AspNet.SignalR.Client.Transports.PollingRequestHandler.<Poll>b__12()
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.<>c__DisplayClass2e.<RunTask>b__2d(Task t)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: stringToEscape
   at System.Uri.EscapeDataString(String stringToEscape)
   at Microsoft.AspNet.SignalR.Client.Transports.TransportHelper.GetReceiveQueryString(IConnection connection, String connectionData, String transport)
   at Microsoft.AspNet.SignalR.Client.Transports.LongPollingTransport.<>c__DisplayClassd.<PollingSetup>b__5()
   at Microsoft.AspNet.SignalR.Client.Transports.PollingRequestHandler.Poll()
   at Microsoft.AspNet.SignalR.Client.Transports.PollingRequestHandler.<Poll>b__12()
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.<>c__DisplayClass2e.<RunTask>b__2d(Task t)<---

AgregateException *******
System.ArgumentNullException: Value cannot be null.
Parameter name: stringToEscape
   at System.Uri.EscapeDataString(String stringToEscape)
   at Microsoft.AspNet.SignalR.Client.Transports.TransportHelper.GetReceiveQueryString(IConnection connection, String connectionData, String transport)
   at Microsoft.AspNet.SignalR.Client.Transports.LongPollingTransport.<>c__DisplayClassd.<PollingSetup>b__5()
   at Microsoft.AspNet.SignalR.Client.Transports.PollingRequestHandler.Poll()
   at Microsoft.AspNet.SignalR.Client.Transports.PollingRequestHandler.<Poll>b__12()
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.<>c__DisplayClass2e.<RunTask>b__2d(Task t)

AgregateException =======

System.ArgumentNullException: Value cannot be null.
Parameter name: stringToEscape
   at System.Uri.EscapeDataString(String stringToEscape)
   at Microsoft.AspNet.SignalR.Client.Transports.TransportHelper.GetReceiveQueryString(IConnection connection, String connectionData, String transport)
   at Microsoft.AspNet.SignalR.Client.Transports.LongPollingTransport.<>c__DisplayClassd.<PollingSetup>b__5()
   at Microsoft.AspNet.SignalR.Client.Transports.PollingRequestHandler.Poll()
   at Microsoft.AspNet.SignalR.Client.Transports.PollingRequestHandler.<Poll>b__12()
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.<>c__DisplayClass2e.<RunTask>b__2d(Task t)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
