### ISSUE TITLE
Error while sending: System.Net.WebSockets.WebSocketException (0x80004005)

### ISSUE THREAD

**Issue by nsulikowski** [SignalR/SignalR#2850]
From a c# client that connects to a Hub in an ASP.NET website, after I see
    `SignalR state change from Connected to Reconnecting`
If I try to call any method in the hub I get the following exception, and the client never reconnects again:

```
Error while sending: System.Net.WebSockets.WebSocketException (0x80004005): The 'System.Net.WebSockets.InternalClientWebSocket' instance cannot be used for communication because it has been transitioned into the 'Aborted' state. ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.WebSocketHelpers.ThrowIfConnectionAborted(Stream connection, Boolean read)
   at System.Net.WebSockets.WebSocketConnectionStream.<WriteAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<SendFrameAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.WebSockets.WebSocketBase.<SendAsyncCore>d__8.MoveNext()
   at System.Net.WebSockets.WebSocketBase.ThrowIfAborted(Boolean aborted, Exception innerException)
   at System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(String methodName, Exception exception, CancellationToken cancellationToken, Boolean aborted)
   at System.Net.WebSockets.WebSocketBase.<SendAsyncCore>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.WebSockets.WebSocketHandler.<<SendAsync>b__0>d__2.MoveNext(); TraceSource 'WaWorkerHost.exe' event
```

**Comment by ryaneliseislalom** [comment]
I'm running version 2.2 and I see the same thing when I run perf test my hub:

...vshost.exe Error: 0 : Error while closing the websocket: System.Net.WebSockets.WebSocketException (0x80004005): An internal WebSocket error occurred. Please see the innerException, if present, for more details.  ---> System.Net.HttpListenerException (0x80004005): An operation was attempted on a nonexistent network connection
   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.WriteAsyncFast(HttpListenerAsyncEventArgs eventArgs)
   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.<WriteAsyncCore>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<SendFrameAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Net.WebSockets.WebSocketBase.<CloseOutputAsyncCore>d__17.MoveNext()
   at System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(String methodName, Exception exception, CancellationToken cancellationToken, Boolean aborted)
   at System.Net.WebSockets.WebSocketBase.<CloseOutputAsyncCore>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNet.SignalR.TaskAwaiterHelper.PreserveCultureAwaiter.GetResult()
   at Microsoft.AspNet.SignalR.WebSockets.WebSocketHandler.<<CloseAsync>b__6>d__8.MoveNext()

**Comment by Prince2690** [comment]
I am using SignalR version 2.2 and i am having the same exceptions on server and not on local server. The SignalR works for 5 to 10 minutes and then below exceptions start logging.

System.Net.WebSockets.WebSocketException (0x80004005): An internal WebSocket error occurred. Please see the innerException, if present, for more details.  ---> System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketConnectionStream.<ReadAsync>d__c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__1.MoveNext()
   at System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(String methodName, Exception exception, CancellationToken cancellationToken, Boolean aborted)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNet.SignalR.WebSockets.WebSocketMessageReader.<ReadMessageAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNet.SignalR.WebSockets.WebSocketHandler.<ProcessWebSocketRequestAsync>d__e.MoveNext()
ExecutionContext.Run => ExecutionContext.RunInternal => <ProcessWebSocketRequestAsync>d__e.MoveNext

**Comment by jkaster** [comment]
One one server, I see the error 100% of the time when trying to send a 1MB block of text with the .NET client SignalR 2.2.1. On a different server, I don't see it. It would really be good to know the cause.
[signalr.trace.txt](https://github.com/SignalR/SignalR/files/974948/signalr.trace.txt)

**Comment by moozzyk** [comment]
You need to debug on the server - looks like the server is closing the connection - most likely due to an exception (the connection is not being closed cleanly).

**Comment by jkaster** [comment]
@moozzyk thanks for the suggestion, but we're talking about identical code behaving differently on one server, working fine on a local instance, and working fine on another remote instance. Also, all exceptions for the Hub and client are logged, so not untrapped exception, and no way the connection is closed without it being detected. All state changes are logged, and trace was even turned on at the client.

**Comment by moozzyk** [comment]
Code might be identical but there are additional factors to consider. The transport used by a client connected to the other servers might be different. The messages the clients sent might be different. For instance you seem to be sending a 1MB message over the websockets transport to the server but the default limit for messages sent over the websockets transport is 64 KB and the server will close the websocket if a message is bigger than that. Have you configured this limit to allow 1MB messages?
Also, if there is an exception on the server side that causes the transport to be closed you won't necessarily get exception details on the client. E.g. when using the websockets transport and the websocket is closed there is no means to send it the details - the client just detects that the websocket was closed.

**Comment by jkaster** [comment]
Thanks for the follow-up @moozzyk. I am logging all ASP.NET exceptions on the SignalR server (hub) side as well, but there's certainly some config on this particular server that's causing issues. When attempting to send the 1MB packet, the client immediately gets the "unexpected disconnect" message from the server. Because my "chunk" size is configurable, I'm going to mess with that first and see if the problem goes away when I drop it down low. Then I can know it's simply an IIS config issue.

**Comment by moozzyk** [comment]
@jkaster - Start from configuring [this](https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Core/Configuration/IConfigurationManager.cs#L46-L51) if you are not doing this already. This is the 64KB limit I was talking about. It applies only to webSockets. If you for instance forgot to turn on webSockets on the other server the clients never use webSockets transport and are not hitting this limit because other transport don't have it.

**Comment by jkaster** [comment]
@moozzyk Thanks so much for the direct source link. I modified my SignalR config and deployed an update to my dev server, and now the block transfers are going fine. I still don't understand why the identical config (I checked IIS on both boxes) and the same code would behave differently, but with your help I was able to resolve the problem.
