### ISSUE TITLE
NullReferenceException from Connection.Stop(TimeSpan timeout)

### ISSUE THREAD

**Issue by eriksundberg** [SignalR/SignalR#2936]
Hi!

Background info:
dotnet: 4.0
SignalR: 1.2

We have two customers that both reported bugs with the same call stack:
System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.AspNet.SignalR.Client.Connection.Stop(TimeSpan timeout)
at Microsoft.AspNet.SignalR.Client.Connection.Stop()
at Microsoft.AspNet.SignalR.Client.Transports.TransportHelper.VerifyLastActive(IConnection connection)
at Microsoft.AspNet.SignalR.Client.Connection.Microsoft.AspNet.SignalR.Client.IConnection.MarkActive()
at Microsoft.AspNet.SignalR.Client.HeartbeatMonitor.Beat()
at Microsoft.AspNet.SignalR.Client.HeartbeatMonitor.<Start>b__0(Object _)
at System.Threading._TimerCallback.TimerCallback_Context(Object state)
at System.Threading.ExecutionContext.runTryCode(Object userData)
at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
at System.Threading._TimerCallback.PerformTimerCallback(Object state)...

We have tried to reproduce it at our site without success. After a very brief check in the code, could it be 

Microsoft.AspNet.SignalR.Client.Connection.Stop(TimeSpan timeout) line 556?

There is a null check for _transport (line 562) after a call to _transport.Abort(...) (line 556).

// Erik

**Comment by maggarwal** [comment]
looks like this is happening again in latest build.

**Comment by moozzyk** [comment]
@maggarwal  - This code has not changes in at least 3 years. If this is happening please open a new issue (this one has already been closed) and provide repro steps.
