### ISSUE TITLE
NullReferenceException in ScaleoutStream.Send

### ISSUE THREAD

**Issue by thomaswr** [SignalR/SignalR#2963]
**Environment**
**WebServer**: Webfarm with 8 nodes, IIS 7.5, .NET 4.0, SignalR 1.2.1, SqlServerScaleOut
**DBMS**: Microsoft SQL Server 2008 R2 (SP2) - 10.50.4000.0 (X64) 
Jun 28 2012 08:36:30 
Copyright (c) Microsoft Corporation
Enterprise Edition (64-bit) on Windows NT 6.1 (Build 7601: Service Pack 1)

**SqlScaleoutConfiguration:**

``` csharp
GlobalHost.DependencyResolver.UseSqlServer(new SqlScaleoutConfiguration(connectionString)
{
    MaxQueueLength = ScaleoutConfiguration.DisableQueuing,
    TableCount = 3
});
```

At **ApplicationStart** we also run this:

``` csharp
TaskScheduler.UnobservedTaskException += (sender, e) =>
{
    e.SetObserved();//to prevent process w3wp.exe crash;
    e.Exception.Handle(ex =>
    {
        var logger = DependencyResolver.Current.GetService<ILog>();
        if (logger != null)
            logger.Error("UnobservedTaskException occured: \n" + ex.Message + " " + ex.Source);
        if (ex.InnerException != null && logger != null)
        {
            logger.Error("UnobservedTaskException InnerException: \n " + ex.InnerException.Message, ex.InnerException);
        }
        Task t = sender as Task;
        if (t != null)
        {
            t.Dispose();
        }

        return true;
    });
};
```

**Description**
Overridden **OnIncomingError** on class derived of **HubPipelineModule** logs this exception occasionally:

```
SignalR Exception: One or more errors occurred.
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func`2 send, Object state)
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.SendImpl(IEnumerator`1 enumerator, TaskCompletionSource`1 taskCompletionSource)
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.Send(IList`1 messages)
   at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message)
   at Microsoft.AspNet.SignalR.ConnectionExtensions.Send(IConnection connection, String connectionId, Object value, String[] excludeConnectionIds)
   at Microsoft.AspNet.SignalR.GroupManager.Add(String connectionId, String groupName)
   at MyApp.Hubs.MyHub.SwitchToGroup(string group)
   at lambda_method(Closure , IHub , Object[] )
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Incoming(IHubIncomingInvokerContext context)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func`2 send, Object state)
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.SendImpl(IEnumerator`1 enumerator, TaskCompletionSource`1 taskCompletionSource)
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.Send(IList`1 messages)
   at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message)
   at Microsoft.AspNet.SignalR.ConnectionExtensions.Send(IConnection connection, String connectionId, Object value, String[] excludeConnectionIds)
   at Microsoft.AspNet.SignalR.GroupManager.Add(String connectionId, String groupName)
   at MyApp.Hubs.MyHub.SwitchToGroup(string group)
   at lambda_method(Closure , IHub , Object[] )
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Incoming(IHubIncomingInvokerContext context)<---
```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
