### ISSUE TITLE
Connections are dropped on the server periodically

### ISSUE THREAD

**Issue by playerx** [SignalR/SignalR#3127]
Hello,

I'm using SignalR for online game and found one issue, on the server connections are dropped periodically with error message:

```
The specified network name is no longer available
```

and once in 24-48 hours, every connection is dropped (without critical error, or application crash) just getting same error, for all connections.

Configuration:

``` js

Server: 'Windows Server 2012 R2'
SSL: 'Yes (but i got same error, when ssl was disabled)'
Protocols: 'WebSockets, LongPolling'
Host: 'Self-hosting, console application'
Version: '2.1.0'
Antivirus: 'No antivirus on server'
```

Error full stack for WebSocket connection:

``` c#
Jok.Matrix.Server.exe Error: 0 : Error while closing the websocket: System.Net.WebSockets.WebSocketException (0x80004005): An internal WebSocket error occurred.
 Please see the innerException, if present, for more details.  ---> System.Net.HttpListenerException (0x80004005): An operation was attempted on a nonexistent network connection
   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.WriteAsyncFast(HttpListenerAsyncEventArgs eventArgs)
   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.<WriteAsyncCore>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<SendFrameAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Net.WebSockets.WebSocketBase.<CloseOutputAsyncCore>d__17.MoveNext()

   at System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(String methodName, Exception exception, CancellationToken cancellationToken, Boolean aborted)
   at System.Net.WebSockets.WebSocketBase.<CloseOutputAsyncCore>d__17.MoveNext()

--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.WebSockets.WebSocketHandler.<<CloseAsync>b__6>d__8.MoveNext()
Jok.Matrix.Server.exe Warning: 0 : SignalR exception thrown by Task: System.AggregateException: One or more errors occurred. ---> System.IO.IOException ---> System.Net.HttpListenerException: The specified network name is no longer available

   at System.Net.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   --- End of inner exception stack trace ---
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNet.SignalR.Owin.ServerResponse.Write(ArraySegment`1 data)
   at Microsoft.AspNet.SignalR.Infrastructure.BinaryTextWriter.<.ctor>b__4(ArraySegment`1 data, Object state)
   at Microsoft.AspNet.SignalR.Infrastructure.BufferTextWriter.ChunkedWriter.Write(ArraySegment`1 data)
   at Microsoft.AspNet.SignalR.Infrastructure.BinaryTextWriter.Write(ArraySegment`1 data)
   at Microsoft.AspNet.SignalR.Transports.PersistentResponse.WriteMessages(TextWriter writer, JsonTextWriter jsonWriter)
   at Microsoft.AspNet.SignalR.Transports.PersistentResponse.Microsoft.AspNet.SignalR.Json.IJsonWritable.WriteJson(TextWriter writer)
   at Microsoft.AspNet.SignalR.Json.JsonSerializerExtensions.Serialize(JsonSerializer serializer, Object value, TextWriter writer)
   at Microsoft.AspNet.SignalR.Transports.LongPollingTransport.PerformPartialSend(Object state)
   at Microsoft.AspNet.SignalR.Transports.LongPollingTransport.<Send>b__2(Object state)
   at Microsoft.AspNet.SignalR.Infrastructure.TaskQueue.InvokeNext(Func`2 next,Object nextState, Object queueState)
   at Microsoft.AspNet.SignalR.Infrastructure.TaskQueue.<Enqueue>b__1(Func`2 n,Object ns, TaskQueue q)
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.FromMethod[T1,T2,T3](Func`4 func, T1 arg1, T2 arg2, T3 arg3)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.Messaging.Subscription.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.Messaging.Subscription.<Work>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.Messaging.MessageBroker.<DoWork>d__2.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.IOException ---> System.Net.HttpListenerException: The specified network name is no longer available
   at System.Net.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   --- End of inner exception stack trace ---
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNet.SignalR.Owin.ServerResponse.Write(ArraySegment`1 data)
   at Microsoft.AspNet.SignalR.Infrastructure.BinaryTextWriter.<.ctor>b__4(ArraySegment`1 data, Object state)
   at Microsoft.AspNet.SignalR.Infrastructure.BufferTextWriter.ChunkedWriter.Write(ArraySegment`1 data)
   at Microsoft.AspNet.SignalR.Infrastructure.BinaryTextWriter.Write(ArraySegment`1 data)
   at Microsoft.AspNet.SignalR.Transports.PersistentResponse.WriteMessages(TextWriter writer, JsonTextWriter jsonWriter)
   at Microsoft.AspNet.SignalR.Transports.PersistentResponse.Microsoft.AspNet.SignalR.Json.IJsonWritable.WriteJson(TextWriter writer)
   at Microsoft.AspNet.SignalR.Json.JsonSerializerExtensions.Serialize(JsonSerializer serializer, Object value, TextWriter writer)
   at Microsoft.AspNet.SignalR.Transports.LongPollingTransport.PerformPartialSend(Object state)
   at Microsoft.AspNet.SignalR.Transports.LongPollingTransport.<Send>b__2(Object state)
   at Microsoft.AspNet.SignalR.Infrastructure.TaskQueue.InvokeNext(Func`2 next,Object nextState, Object queueState)
   at Microsoft.AspNet.SignalR.Infrastructure.TaskQueue.<Enqueue>b__1(Func`2 n,Object ns, TaskQueue q)
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.FromMethod[T1,T2,T3](Func`4 func, T1 arg1, T2 arg2, T3 arg3)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.Messaging.Subscription.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.Messaging.Subscription.<Work>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.Messaging.MessageBroker.<DoWork>d__2.MoveNext()<-
--
```

also I've full-stack for long polling connection, which is similar.

do you have any idea why this should happen?

Thanks.

**Comment by EnCey** [comment]
@DamianEdwards There is a newer comment in the [linked connect issue](https://connect.microsoft.com/VisualStudio/feedback/details/878518/httplistener-bug) that states that » _[…] the exception is "by design" and should be handled by the application or the library (such as OWIN)._ « . 
Thus it may have to be handled by SignalR?
