### ISSUE TITLE
NullReferenceException (Booksleeve -> StackExchange.Redis migration)

### ISSUE THREAD

**Issue by timc13** [SignalR/SignalR#3173]
I've been trying the dev branch now that the stackexchange.redis lib has been merged.  (need to reconnect in a redis failover scenario)  However, my IIS worker process keeps crashing due to this an unhandled exception:

```
Exception: System.NullReferenceException

Message: Object reference not set to an instance of an object.

StackTrace:    at System.Web.ThreadContext.AssociateWithCurrentThread(Boolean setImpersonationContext)
at System.Web.HttpApplication.OnThreadEnterPrivate(Boolean setImpersonationContext)
at System.Web.LegacyAspNetSynchronizationContext.CallCallbackPossiblyUnderLock(SendOrPostCallback callback, Object state)
at System.Web.LegacyAspNetSynchronizationContext.CallCallback(SendOrPostCallback callback, Object state)
at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location where exception was thrown ---
at System.Threading.Tasks.AwaitTaskContinuation.<ThrowAsyncIfNecessary>b__1(Object s)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

I'm certain this is due to the stackexchange migration because, 1) this wasn't happening in the dev branch before the merge, and 2) this doesn't happen when I remove the redis backplane configuration.  Any help would be appreciated.

**Comment by ejsmith** [comment]
I am getting this issue and it's trying me nuts.

**Comment by BrennanConroy** [comment]
Could you give more information. Do you have a repo? Did this issue recently show up? What changed if it did?

**Comment by abergs** [comment]
We are running in to this issue as well.
We're running with the Redis Backplane.
I'm able to repro by start Asp.net API + JS Client up. Then stopping the asp.net server and launching it again. On the negotiate request we get this exception:

System.NullReferenceException occurred
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.

StackTrace	"   at System.Web.ThreadContext.AssociateWithCurrentThread(Boolean setImpersonationContext)"	string

Will try to disable the redis backplane and see if that changes anything
