### ISSUE TITLE
missing security attributes

### ISSUE THREAD

**Issue by BrannonKing** [SignalR/SignalR#3207]
When I attempt to profile a .NET client application (v2.1.0) I get this error from Ants Performance Profiler v8:

```
2014-08-11T14:22:14.550 [2] ERROR Asi.Ui.Client.MobiusApplication - System.MethodAccessException: Attempt by security transparent method 'System.Net.Http.HttpClientHandler+WebExceptionWrapperStream.ReadAsync(Byte[], Int32, Int32, System.Threading.CancellationToken)' to call native code through method '<Module>._ANTS_Begin_Async()' failed.  Methods must be security critical or security safe-critical to call native code.
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.Net.Http.DelegatingStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNet.SignalR.Client.Transports.AsyncStreamReader.Process()
   at Microsoft.AspNet.SignalR.Client.Transports.AsyncStreamReader.Start()
   at Microsoft.AspNet.SignalR.Client.Http.IResponseExtensions.ReadAsString(IResponse response, Func`2 onChunk)
   at Microsoft.AspNet.SignalR.Client.Http.IResponseExtensions.ReadAsString(IResponse response)
   at Microsoft.AspNet.SignalR.Client.Transports.TransportHelper.<GetNegotiationResponse>b__0(IResponse response)
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.<>c__DisplayClass15`2.<Then>b__13(Task`1 t)
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.TaskRunners`2.<>c__DisplayClass3a.<RunTask>b__39(Task`1 t)
```

**Comment by aliveli186** [comment]
@jessica-ramos That line doesn't work for ANTS Performance Profiler 9

`<assemblyName>System.Net.Http.dll</assemblyName>`

**Comment by jessica-ramos** [comment]
Hi @aliveli186 

So sorry- it should actually be without the .dll extension:

<assemblyName>System.Net.Http</assemblyName>

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
