### ISSUE TITLE
A lot of HttpExceptions: The remote host closed the connection. The error code is 0x80070057.

### ISSUE THREAD

**Issue by alex-simonov** [SignalR/SignalR#3296]
Hello.
After upgrade from 2.0.3 to 2.1.2 I see a lot of errors like this in ELMAH:

```
System.Web.HttpException (0x80070057): The remote host closed the connection. The error code is 0x80070057.
   at System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect)
   at System.Web.Hosting.IIS7WorkerRequest.ExplicitFlush()
   at System.Web.HttpResponse.Flush(Boolean finalFlush, Boolean async)
   at System.Web.HttpWriter.WriteFromStream(Byte[] data, Int32 offset, Int32 size)
   at Microsoft.Owin.Host.SystemWeb.CallStreams.OutputStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNet.SignalR.Owin.ServerResponse.Write(ArraySegment`1 data)
   at Microsoft.AspNet.SignalR.Hosting.ResponseExtensions.End(IResponse response, String data)
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.GenericDelegates`5.<>c__DisplayClass4f.<ThenWithArgs>b__4e()
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.TaskRunners`2.<>c__DisplayClass3a.<RunTask>b__39(Task t)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Mapping.MapMiddleware.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.<RunApp>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.<DoFinalWork>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

Is there any way to turn these errors off? May be you can check that socket is open before writing response to it or catch these exceptions in your code? In my application approximately every minute occurs about 5-10 similar errors. They bother me to react to truly important errors.

Urls that can throw such exception:

```
/signalr/hubs
/signalr/negotiate
/signalr/start
```

P.S. I found a similar issue https://github.com/SignalR/SignalR/issues/1790, but the proposed solution does not fit to me. SignalR is the only component that throws such exceptions. There are no similar exceptions niehther from ASP.NET MVC, nor from WebAPI.

**Comment by alex-simonov** [comment]
Same for 2.2.0. Is there any way to catch/handle such exceptions? Should I handle them?

**Comment by oliveiracdz** [comment]
Hi Alex,

Any news about?

Tks!

**Comment by alex-simonov** [comment]
Hi, @oliveiracdz.
There are no changes, exceptions are still there.

**Comment by avantida** [comment]
There should be a try-catch around this code
https://github.com/SignalR/SignalR/blob/1fba14fa3437e24c204dfaf8a18db3fce8acad3c/src/Microsoft.AspNet.SignalR.Core/Owin/ServerResponse.cs#L46

Or the framework should capture the exception up the stack and remove/flag the client as no longer 'there'?

**Comment by michaelschmit** [comment]
I am currently running into this issue on 2.2.1.  We are in the process of upgrading to 2.2.3.  I will report back on whether this continues to be an issue or not.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
