### ISSUE TITLE
System.Net.HttpListenerException when writing to an already disconnected client

### ISSUE THREAD

**Issue by sboele** [SignalR/SignalR#3329]
Hello,

One of our clients is getting a lot of exceptions on a SignalR self hosted instance. The error happens quite often like every 3-4 minutes.

Stacktrace of the exception is:

```
--Section Child Level: 1----------------------------------------------------------------------------------------------------------
ExceptionType : System.AggregateException
Source        :
Message       : A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

Stacktrace    :

--Section Child Level: 2----------------------------------------------------------------------------------------------------------
ExceptionType : System.IO.IOException
Source        : Microsoft.Owin.Host.HttpListener
Message       :

Stacktrace    :
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNet.SignalR.Owin.ServerResponse.Write(ArraySegment`1 data)
   at Microsoft.AspNet.SignalR.Infrastructure.BinaryTextWriter.<.ctor>b__4(ArraySegment`1 data, Object state)
   at Microsoft.AspNet.SignalR.Infrastructure.BufferTextWriter.ChunkedWriter.Flush(Byte[] byteBuffer, Boolean flushEncoder)
   at Microsoft.AspNet.SignalR.Infrastructure.BufferTextWriter.ChunkedWriter.Write(String value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.AspNet.SignalR.Transports.LongPollingTransport.PerformSend(Object state)
   at Microsoft.AspNet.SignalR.Infrastructure.TaskQueue.<Enqueue>b__1(Func`2 next, Object nextState)
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.FromMethod[T1,T2](Func`3 func, T1 arg1, T2 arg2)
--Section Child Level: 3----------------------------------------------------------------------------------------------------------
ExceptionType : System.Net.HttpListenerException
Source        : System
Message       : The specified network name is no longer available

Stacktrace    :
   at System.Net.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.Write(Byte[] buffer, Int32 offset, Int32 count)
--End-----------------------------------------------------------------------------------------------------------------------------

 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.IO.IOException ---> System.Net.HttpListenerException: The specified network name is no longer available
   at System.Net.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.Write(Byte[] buffer, Int3..."
```

The issue seems to happen when the server tries to write to a client that is already disconnected.

**Comment by BrannonKing** [comment]
This is generally not an unexpected exception. Most transports don't fail until there is some data sent on it. This exception is there to let you know that your client is no longer there and data we tried to send to it failed. You need to wait for this exception when sending any events on the server. (The `dynamic` objects return `Task`.) Most of the time, the server doesn't need to do anything. It can just eat the exception. Occasionally, you have a situation where you need to react to a client being gone. 

Random disconnects happen, even on the best of networks. The client needs to query the full state whenever its hub is connected.

**Comment by halter73** [comment]
From looking at the stack trace, it appears that SignalR is trying to write the return value of a Hub method unless `Transport.Send(object)` is being called directly from a `PersistentConnection`.

In this case, SignalR should be observing the faulted task, since the end user has no opportunity to do so outside of maybe a `HubPipelindModule`.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
