### ISSUE TITLE
Azure Redis Backplane: Web role communication loss with backplane

### ISSUE THREAD

**Issue by Barbu666** [SignalR/SignalR#3364]
We are currently running 3 web roles inside an Azure Cloud Service backed by an Azure Redis Cache backplane. We've run with this setup for about 2 weeks in production without any issues. Last weekend , 1 of the instance appears to have lost its connections with the backplane and was unable to recover until the web server was rebooted. The redis server was running properly as the two other web roles were working just fine. This is the stacktrace we found in the logs: 

The connection has been closed (Error); no new messages can be delivered; the last command was sent 60840625ms ago

   at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func`2 send, Object state)
   at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message)
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Outgoing(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass1b.<BuildOutgoing>b__19(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipeline.Send(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.SignalProxy.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
...

If I'm not mistaken that error message is from BookSleeve and not SignalR itself. Have you ever experienced something similar or have any idea of what could have caused this?

Thanks

**Comment by DamianEdwards** [comment]
Haven't seen this before but with the release of 2.2.0 we've moved our Redis support to using StackExchange.Redis instead of Booksleeve. I'd encourage you to try 2.2.0 and see if it addresses this issue.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
