### ISSUE TITLE
Bug: Unable to declare state variables as properties in client interface you want to pass to Hub<T>

### ISSUE THREAD

**Issue by mansoor-omrani** [SignalR/SignalR#3441]
It seems that when you intend to derive your hub class from Hub&lt;T&gt;, you can only declare client-methods in the interface of client. You won't be able to declare state variables as properties in that interface. On the other hand, you will not be able to use them on Clients.Caller, because it is no longer a dynamic object. This brings you to a one choice out of the two: either use Hub&lt;T&gt; or state variables, but not both.

The interface 'IChatClient' must not contain any properties.

at Microsoft.AspNet.SignalR.Hubs.TypedClientBuilder`1.VerifyInterface(Type interfaceType)
at Microsoft.AspNet.SignalR.Hubs.TypedClientBuilder`1.GenerateClientBuilder()
at Microsoft.AspNet.SignalR.Hubs.TypedClientBuilder`1.<.cctor>b__13()
at System.Lazy`1.CreateValue()
at System.Lazy`1.LazyInitValue()
at System.Lazy`1.get_Value()
at Microsoft.AspNet.SignalR.Hubs.TypedClientBuilder`1.Build(IClientProxy proxy)
at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
at Microsoft.AspNet.SignalR.Hubs.TypedHubCallerConnectionContext`1.get_Caller()
at ChatV2.ChatHub.Send(String message)
in ...\ChatHub.cs:line 44
at lambda_method(Closure , IHub , Object[] )
at Microsoft.AspNet.SignalR.Hubs.HubMethodDispatcher.<>c__DisplayClass1.<WrapVoidAction>b__0(IHub hub, Object[] parameters)
at Microsoft.AspNet.SignalR.Hubs.HubMethodDispatcher.Execute(IHub hub, Object[] parameters)
at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Incoming(IHubIncomingInvokerContext context)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass1.<<BuildIncoming>b__0>d__3.MoveNext()"}

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
