### ISSUE TITLE
Inconsistent error handling depending on if hub methods are marked as async or not.

### ISSUE THREAD

**Issue by ash23** [SignalR/SignalR#3454]
I am throwing HubExceptions from my hub methods for invalid input method arguments etc. I have noticed that in order for the HubException (or any other exception) to be handled by SignalR the hub method must not be marked as async. If marked as async the HubException is not caught and hence my Windows service hosting SignalR is terminated since an unhandled exception was thrown. 
Also OnIncomingError() my registered HubPipelineModule is not being invoked when an exception is thrown from a hub method marked as async.

For me this is not a big issue since I really don't need any hub method to be marked as async but reporting it here since it is resulting in inconsistent error handling behavior from SignalR.

SignalR version: 2.2.0.0

See below stack traces for more info:

Exception is unhandled when the Hub method is marked as async (resulting in termination of my Windows service hosting it):

  at Foo.Bar.Hubs.MyHub.<MyAsyncHubMethod>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Exception is properly handled when the Hub method not marked as async and HubPipelineModule.OnIncomingError() on my registered HubPipelineModule is invoked as expected:

  at Foo.Bar.Hubs.MyHub.MySynchronousHubMethod(String argA, String argB)
   at lambda_method(Closure , IHub , Object[] )
   at Microsoft.AspNet.SignalR.Hubs.HubMethodDispatcher.<>c__DisplayClass1.<WrapVoidAction>b__0(IHub hub, Object[] parameters)
   at Microsoft.AspNet.SignalR.Hubs.HubMethodDispatcher.Execute(IHub hub, Object[] parameters)
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Incoming(IHubIncomingInvokerContext context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass1.<<BuildIncoming>b__0>d__3.MoveNext()

**Comment by moozzyk** [comment]
Have you tried returning a faulted task in the async method instead of throwing?

**Comment by Fadi-git** [comment]
I ran into the same issue, and it turned out that hub's async method return void, while it must return Task in order to handle HubException by SignalR.

**Comment by mwenk** [comment]
Is there any update on that? Ran into the same Problem today.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
