### ISSUE TITLE
System.FormatException Invalid Cursor on reconnect request

### ISSUE THREAD

**Issue by cwt237** [SignalR/SignalR#3513]
We have a SignalR 2.0.3 solution running, where a System.FormatException is thrown on a reconnect request (ServerSentEvents):

```
System.FormatException: Invalid cursor.
   at Microsoft.AspNet.SignalR.Messaging.Cursor.GetCursors(String cursor, String prefix, Func`3 keyMaximizer, Object state)
   at Microsoft.AspNet.SignalR.Messaging.DefaultSubscription..ctor(String identity, IList`1 eventKeys, TopicLookup topics, String cursor, Func`3 callback, Int32 maxMessages, IStringMinifier stringMinifier, IPerformanceCounterManager counters, Object state, Boolean ignoreMessageLoss, String messageLossMessage)
   at Microsoft.AspNet.SignalR.Messaging.MessageBus.CreateSubscription(ISubscriber subscriber, String cursor, Func`3 callback, Int32 messageBufferSize, Object state)
   at Microsoft.AspNet.SignalR.Messaging.MessageBus.Subscribe(ISubscriber subscriber, String cursor, Func`3 callback, Int32 maxMessages, Object state)
   at Microsoft.AspNet.SignalR.Infrastructure.Connection.Receive(String messageId, Func`3 callback, Int32 maxMessages, Object state)
   at Microsoft.AspNet.SignalR.Transports.ForeverTransport.ProcessMessages(ITransportConnection connection, Func`1 initialize)
```

It seems to be related to the message id in the GET request for the reconnect. The first 2 reconnect requests work fine and then the next 5 fails with this exception being thrown:

```
GET "/xxx/negotiate" "clientProtocol=1.3&_=1436405167018" 80 200
GET "/xxx/connect" "transport=serverSentEvents&connectionToken=hpcSNQuDpIg1QTNgvUgT2birT%2FV7ZbRBh2mb8etJ6SHJ4soWv0zv%2B%2BwMXcHqm7gRJoEsxCKYBUj2VhbO7C4tRGXYrGPxiTUwrzwq%2BwkVAoeFDos9&authorization=xyz&tid=0" 80 200 
GET "/xxx/reconnect" "transport=serverSentEvents&connectionToken=hpcSNQuDpIg1QTNgvUgT2birT%2FV7ZbRBh2mb8etJ6SHJ4soWv0zv%2B%2BwMXcHqm7gRJoEsxCKYBUj2VhbO7C4tRGXYrGPxiTUwrzwq%2BwkVAoeFDos9&messageId=d-4B952065-E0%2C0%7CHnB%2C37%7CHnC%2C0&authorization=xyz&tid=7" 80 400
GET "/xxx/reconnect" "transport=serverSentEvents&connectionToken=hpcSNQuDpIg1QTNgvUgT2birT%2FV7ZbRBh2mb8etJ6SHJ4soWv0zv%2B%2BwMXcHqm7gRJoEsxCKYBUj2VhbO7C4tRGXYrGPxiTUwrzwq%2BwkVAoeFDos9&messageId=d-4B952065-E0%2C0%7CHnB%2C37%7CHnC%2C0&authorization=xyz&tid=10" 80 400
GET "/xxx/reconnect" "transport=serverSentEvents&connectionToken=hpcSNQuDpIg1QTNgvUgT2birT%2FV7ZbRBh2mb8etJ6SHJ4soWv0zv%2B%2BwMXcHqm7gRJoEsxCKYBUj2VhbO7C4tRGXYrGPxiTUwrzwq%2BwkVAoeFDos9&messageId=d-4B952065-&authorization=xyz&tid=4" 80 400
GET "/xxx/reconnect" "transport=serverSentEvents&connectionToken=hpcSNQuDpIg1QTNgvUgT2birT%2FV7ZbRBh2mb8etJ6SHJ4soWv0zv%2B%2BwMXcHqm7gRJoEsxCKYBUj2VhbO7C4tRGXYrGPxiTUwrzwq%2BwkVAoeFDos9&messageId=d-4B952065-&authorization=xyz&tid=1" 80 400
GET "/xxx/reconnect" "transport=serverSentEvents&connectionToken=hpcSNQuDpIg1QTNgvUgT2birT%2FV7ZbRBh2mb8etJ6SHJ4soWv0zv%2B%2BwMXcHqm7gRJoEsxCKYBUj2VhbO7C4tRGXYrGPxiTUwrzwq%2BwkVAoeFDos9&messageId=d-4B952065-&authorization=xyz&tid=4" 80 400
GET "/xxx/reconnect" "transport=serverSentEvents&connectionToken=hpcSNQuDpIg1QTNgvUgT2birT%2FV7ZbRBh2mb8etJ6SHJ4soWv0zv%2B%2BwMXcHqm7gRJoEsxCKYBUj2VhbO7C4tRGXYrGPxiTUwrzwq%2BwkVAoeFDos9&messageId=d-4B952065-&authorization=xyz&tid=8" 80 400
GET "/xxx/reconnect" "transport=serverSentEvents&connectionToken=hpcSNQuDpIg1QTNgvUgT2birT%2FV7ZbRBh2mb8etJ6SHJ4soWv0zv%2B%2BwMXcHqm7gRJoEsxCKYBUj2VhbO7C4tRGXYrGPxiTUwrzwq%2BwkVAoeFDos9&messageId=d-4B952065-&authorization=xyz&tid=2" 80 400
```

It might be a client problem? (Chrome browser on Windows desktop using SignalR 2.0.3 client library).

It seems like this should not be a format exception, but translated into a custom validation exception (if the client indeed has manipulated the message id parameter).

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
