### ISSUE TITLE
Azure CloudService: SecurityException when writting to SignalR.ServiceBusMessageBus source

### ISSUE THREAD

**Issue by Unrefraction** [SignalR/SignalR#3527]
Sorry if this issue had already been raised.
I tried to search for a similar issues but didn't find any.

Our app is hosted in Azure Cloud Service.
In order to improve logging and possible issue investigation I enabled tracing like it is described in documentation and deployed app.
But web role began recycling and after examining azure logs I found next:

```
Exception: System.Security.SecurityException

Message: The source was not found, but some or all event logs could not be searched.  To create the source, you need permission to read all event logs to make sure that the new source name is unique.  Inaccessible logs: Security.

StackTrace:    at System.Diagnostics.EventLog.FindSourceRegistration(String source, String machineName, Boolean readOnly, Boolean wantToCreate)
   at System.Diagnostics.EventLog.SourceExists(String source, String machineName, Boolean wantToCreate)
   at System.Diagnostics.EventLogInternal.VerifyAndCreateSource(String sourceName, String currentMachineName)
   at System.Diagnostics.EventLogInternal.WriteEvent(EventInstance instance, Byte[] data, Object[] values)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String format, Object[] args)
   at Microsoft.AspNet.SignalR.ServiceBus.ServiceBusConnection.Subscribe(ServiceBusConnectionContext connectionContext)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

As I understand, application doesn't have enought permission.

I found an article that describes how to create custome event source by running startup task, but is there any other way to resolve this issue?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
