### ISSUE TITLE
SignalR Scaleout Redis cluster master/slave issue

### ISSUE THREAD

**Issue by bp74** [SignalR/SignalR#3564]
We are running a SignalR service on load balanced web servers and on a single windows service instance. The windows services creates broadcast messages and the web servers will broadcast those messages. Everything is working fine, except one problem we cannot solve.

The SignalR Scaleout backplane is using a Redis cluster running on Linux. We have 3 Redis nodes with a master and two slaves. The Redis connection string looks like this:

```
lx-redis01.company.local:6379,lx-redis02.company.local:6379,lx-redis03.company.local:6379,abortConnect=false,connectRetry=10,ConnectTimeout=500
```

From time to time we get this exception:

```
StackExchange.Redis.RedisServerException: ERR Error running script (call to f_5b8e3b60e050400311bc8b6ef2cbba37bc0b9cb3): @user_script:1: @user_script: 1: -READONLY You can't write against a read only slave.   
```

The problem is obviously that the SignalR Scaleout backplane tries to write to a slave on the Redis cluster. Once this exception occurs it never goes away. We have to restart the windows service to force a reconnect to the Redis cluster. The restart solves the problem.

Does anyone have some insight what is going on? I looked at the SignalR Scaleout backplane for Redis but the API is very minimal and there is nothing we can do to fix this issue.

**Comment by bp74** [comment]
This is the complete stack trace:

    StackExchange.Redis.RedisServerException: ERR Error running script (call to f_5b8e3b60e050400311bc8b6ef2cbba37bc0b9cb3): @user_script:1: @user_script: 1: -READONLY You can't write against a read only slave.   
       at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func`2 send, Object state)
       at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message)
       at Microsoft.AspNet.SignalR.ConnectionExtensions.Send(IConnection connection, String connectionId, Object value)
       at Microsoft.AspNet.SignalR.GroupManager.Add(String connectionId, String groupName)
       at (our code)

    StackExchange.Redis.RedisServerException: ERR Error running script (call to f_5b8e3b60e050400311bc8b6ef2cbba37bc0b9cb3): @user_script:1: @user_script: 1: -READONLY You can't write against a read only slave.   
       at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func`2 send, Object state)
       at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message)
       at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Outgoing(IHubOutgoingInvokerContext context)
       at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass1b.<BuildOutgoing>b__19(IHubOutgoingInvokerContext context)
       at Microsoft.AspNet.SignalR.Hubs.HubPipeline.Send(IHubOutgoingInvokerContext context)
       at Microsoft.AspNet.SignalR.Hubs.SignalProxy.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
       at CallSite.Target(Closure , CallSite , Object , Object )
      at (our code)

**Comment by undecided2013** [comment]
Hmm, is this being addressed? I was planning to use a similar topology

**Comment by bp74** [comment]
Unfortunately this issue is not resolved. But we patched the SignalR Redis backplane by adding a try-catch and by creating a new Redis ConnectionMultiplexer in case of an error which works okay.

**Comment by shykln** [comment]
Hi @bp74 , would you like to share what you have patched in the source code? We face the same problem but have no clue how to fix it in the code.

Thanks a million!

**Comment by bp74** [comment]
What we did is basically adding a try-catch in the Send method of RedisMessageBus.cs. In case of the exception we create a new instance of RedisConnection (see variable _connection) and do a reconnect (see method ConnectWithRetry), which seems to connect to the master reliably (and not to the slave) which is a workaround for the problem.

**Comment by moozzyk** [comment]
This sounds a lot like this issue https://github.com/SignalR/SignalR/issues/3093 where if `Send` fails the error is being replayed and the connection is never re-established. This was fixed in 2.2.2.

**Comment by msinha53** [comment]
I am getting the same issue in 2.2.2. 
stack:UTC:2017-08-18 13:44:29,693 [72] ERROR StackExchange.Redis.RedisServerException: ERR Error running script (call to f_5b8e3b60e050400311bc8b6ef2cbba37bc0b9cb3): @user_script:1: @user_script: 1: -READONLY You can't write against a read only slave.   
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func`2 send, Object state)
   at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message)
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Outgoing(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass6_0.<BuildOutgoing>b__0(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass6_0.<BuildOutgoing>b__0(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.SignalProxy.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure , CallSite , Object , RealTimeData , RtsRealTimeSubscription )
   at ChannelHub.Notify(RealTimeDataEx realTimeDataEx) in 

The App Pool restart solves the problem.

**Comment by AshishShukla16** [comment]
I am facing the similar problem hare, but on the OnConnected event of SignalR hub. Inside the OnConnected event handler I am storing the user's connection details in the redis server. But client is not able to connect to the SignalR server. I have enabled the Redis backplane with SignalR setup and my redis is configured in cluster mode on Linux servers. 
Here in the Microsoft documentation it's mentioned that "SignalR scaleout with Redis does not support Redis clusters." https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/scaleout-with-redis. So what should be done to scale out signalR using Redis?
