### ISSUE TITLE
PersistentConnection js client bugs.

### ISSUE THREAD

**Issue by niemyjski** [SignalR/SignalR#3581]
We recently moved to use the PersistentClient in our client side app and I'm noticing lots of client exceptions since we deployed (over 10k). I haven't been able to reproduce locally but looking at the code it kinda makes sense why it's blowing up..

## Code
We based it off [these docs](https://github.com/SignalR/SignalR/wiki/QuickStart-Persistent-Connections)

#### Client
https://github.com/exceptionless/Exceptionless.UI/blob/master/src/components/signalr/signalr-service.js#L24-L57

#### Server

https://github.com/exceptionless/Exceptionless/blob/master/Source/Api/AppBuilder.cs#L149
https://github.com/exceptionless/Exceptionless/tree/master/Source/Api/Hubs

## Errors:
```is
TypeError: Cannot read property 'toLowerCase' of undefined
at Object.<anonymous>()
at Object.<anonymous>()
at Object.n.event.dispatch() in https://code.jquery.com/jquery-2.1.4.min.js:line 3:col 6466
at Object.r.handle() in https://code.jquery.com/jquery-2.1.4.min.js:line 3:col 3241
at Object.n.event.trigger() in https://code.jquery.com/jquery-2.1.4.min.js:line 3:col 5574
at n.fn.extend.triggerHandler() in https://code.jquery.com/jquery-2.1.4.min.js:line 3:col 11623
at Object.i.transports._logic.triggerReceived()
at Object.<anonymous>() 
at Function.n.extend.each() in https://code.jquery.com/jquery-2.1.4.min.js:line 2:col 2882
at Object.i.transports._logic.processMessages() 
at WebSocket.b.WebSocket.c.socket.c.socket.onmessage() 
```

```js
TypeError: c.Hub is undefined
at j.fn.init/<()
at i.prototype.received/<()
at n.event.dispatch() in https://code.jquery.com/jquery-2.1.4.min.js:line 3:col 6414
at n.event.add/r.handle() in https://code.jquery.com/jquery-2.1.4.min.js:line 3:col 3224
at n.event.trigger() in https://code.jquery.com/jquery-2.1.4.min.js:line 3:col 5572
at .triggerHandler() in https://code.jquery.com/jquery-2.1.4.min.js:line 3:col 11615
at i.transports._logic.triggerReceived()
at i.transports._logic.processMessages/<()
at .each()
at i.transports._logic.processMessages() 
at d.transports.webSockets.start/c.socket.onmessage()
```

I tracked the code and it's breaking here:
https://github.com/SignalR/SignalR/blob/master/src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.hubs.js#L305-L308

I'm not sure why this hub code is ever being called as I'm not explicitly calling any hub connection logic. Ideas?

**Comment by niemyjski** [comment]
I'm closing this as I think that these may be coming from users who may be running an old client version. If I rule this out that this isn't the case I'll reopen this issue.
