### ISSUE TITLE
Heartbeat may trigger while Connection.Stop() is still running.

### ISSUE THREAD

**Issue by josteink** [SignalR/SignalR#3602]
We're experiencing an issue in our SignalR-based client that while we're calling [Connection.Stop()](https://github.com/SignalR/SignalR/blob/master/src/Microsoft.AspNet.SignalR.Client/Connection.cs#L608) in a multithreaded environment, we can still get events triggered from SignalR.

Consider the following (sanitized) eventlog entry and stack-trace:

```
Application: SuperOffice.SignalRClient.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
Stack:
   SuperOffice.SignalRClient.ClientClass.AssertNotDisposed()
   ....
   at SuperOffice.SignalRClient.ClientClass.Connection_StateChanged(Microsoft.AspNet.SignalR.Client.StateChange)
   at Microsoft.AspNet.SignalR.Client.Connection.set_State(Microsoft.AspNet.SignalR.Client.ConnectionState)
   at Microsoft.AspNet.SignalR.Client.Connection.Disconnect()
   at Microsoft.AspNet.SignalR.Client.Connection.Stop(System.TimeSpan)
   at Microsoft.AspNet.SignalR.Client.Connection.Microsoft.AspNet.SignalR.Client.IConnection.MarkActive()
   at Microsoft.AspNet.SignalR.Client.HeartbeatMonitor.Beat()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

This exception is happening as the connection is being stopped/disposed.

This is clearly being done by the HearbeatMonitor.

Looking at the relevant code in Connection.cs, we can see that SignalR attempts to process the existing queues and lots of other time-consuming stuff before [finally stopping the HeartbeatMonitor](https://github.com/SignalR/SignalR/blob/master/src/Microsoft.AspNet.SignalR.Client/Connection.cs#L640-L643).

Shouldn't stopping the HeartbeatMonitor be the first thing SignalR should be doing when it receives an intent to stop the connection? Or is the order in which the class is being unloaded specificly like this for a reason?

**Comment by josteink** [comment]
We've rewritten the application and the way SignalR is used (with a supervisor/scheduler class) so this is no longer an issue. Closing issue.
