### ISSUE TITLE
OutOfMemoryException after all client disconnected

### ISSUE THREAD

**Issue by xiaodm** [SignalR/SignalR#3612]
Hi ,
   i have a problem,   the signalR server throw OutOfMemoryException  after all client disconnected(may be the network error triggers the ondisconnected event, ).  
the signalR version is : 2.0.0.0  
the client count :   50  
 whats the problem?  
the exception:   

```
Exception of type 'System.OutOfMemoryException' was thrown.
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func`2 send, Object state)
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutStreamManager.Send(Int32 streamIndex, IList`1 messages)
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.Send(IList`1 messages)
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.Publish(Message message)
   at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message)
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Outgoing(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass1b.<BuildOutgoing>b__19(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass1b.<BuildOutgoing>b__19(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipeline.Send(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.ClientProxy.Invoke(String method, Object[] args)
   at Microsoft.AspNet.SignalR.Hubs.ClientProxy.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure , CallSite , Object , String )
   at Gs.SeatAndNotice.Portal.Hubs.CoreHub.OnDisconnected()
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Disconnect(IHub hub)
   at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass13.<BuildDisconnect>b__11(IHub hub)
   at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass13.<BuildDisconnect>b__11(IHub hub)
   at Microsoft.AspNet.SignalR.Hubs.HubPipeline.Disconnect(IHub hub)
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.<OnDisconnected>b__21(IHub hub)
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.<>c__DisplayClass2a.<ExecuteHubEvent>b__26(IHub instance)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.ExecuteHubEvent(IRequest request, String connectionId, Func`2 action)
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.OnDisconnected(IRequest request, String connectionId)
   at Gs.SeatAndNotice.Portal.Connection.SeatConnection.OnDisconnected(IRequest request, String connectionId)
   at Microsoft.AspNet.SignalR.PersistentConnection.<>c__DisplayClassa.<ProcessRequest>b__9()
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.FromMethod(Func`1 func)  
```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
