### ISSUE TITLE
Uri string is too long on BuildReconnect

### ISSUE THREAD

**Issue by dejean7777** [SignalR/SignalR#3686]
If I leave my SignalR connection active long enough, eventually I'll get something like this. I'm gathering more information, but I wasn't able to figure out where exactly this happens. Annoying thing is, not under my control. Not sure how to handle this, as it'll take my process down.

System.UriFormatException: Invalid URI: The Uri string is too long.
   at System.UriHelper.EscapeString(String input, Int32 start, Int32 end, Char[] dest, Int32& destPos, Boolean isUriString, Char force1, Char force2, Char rsvd)
   at System.Uri.EscapeDataString(String stringToEscape)
   at Microsoft.AspNet.SignalR.Client.Infrastructure.UrlBuilder.AppendGroupsToken(StringBuilder urlStringBuilder, IConnection connection)
   at Microsoft.AspNet.SignalR.Client.Infrastructure.UrlBuilder.BuildReconnect(IConnection connection, String transport, String connectionData)
   at Microsoft.AspNet.SignalR.Client.Transports.WebSocketTransport.<DoReconnect>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
System.UriFormatException: Invalid URI: The Uri string is too long.
   at System.UriHelper.EscapeString(String input, Int32 start, Int32 end, Char[] dest, Int32& destPos, Boolean isUriString, Char force1, Char force2, Char rsvd)
   at System.Uri.EscapeDataString(String stringToEscape)
   at Microsoft.AspNet.SignalR.Client.Infrastructure.UrlBuilder.AppendGroupsToken(StringBuilder urlStringBuilder, IConnection connection)
   at Microsoft.AspNet.SignalR.Client.Infrastructure.UrlBuilder.BuildReconnect(IConnection connection, String transport, String connectionData)
   at Microsoft.AspNet.SignalR.Client.Transports.WebSocketTransport.<DoReconnect>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Unhandled Exception: System.UriFormatException: Invalid URI: The Uri string is too long.
   at System.UriHelper.EscapeString(String input, Int32 start, Int32 end, Char[] dest, Int32& destPos, Boolean isUriString, Char force1, Char force2, Char rsvd)
   at System.Uri.EscapeDataString(String stringToEscape)
   at Microsoft.AspNet.SignalR.Client.Infrastructure.UrlBuilder.AppendGroupsToken(StringBuilder urlStringBuilder, IConnection connection)
   at Microsoft.AspNet.SignalR.Client.Infrastructure.UrlBuilder.BuildReconnect(IConnection connection, String transport, String connectionData)
   at Microsoft.AspNet.SignalR.Client.Transports.WebSocketTransport.<DoReconnect>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by moozzyk** [comment]
Is this because the client is being added to many groups overtime and the groups token is getting too big?

**Comment by dejean7777** [comment]
Not sure, there shouldn't be any need to add the client to any groups. This is a client-side exception, in the signalr client.

**Comment by moozzyk** [comment]
Looks like the client is added to many groups as per your stack trace:  

```
at Microsoft.AspNet.SignalR.Client.Infrastructure.UrlBuilder.AppendGroupsToken(StringBuilder urlStringBuilder, IConnection connection)
```

This is currently a limitation and there isn't a good workaround. Related issue: https://github.com/SignalR/SignalR/issues/3400

**Comment by dejean7777** [comment]
Yeah, not sure why the backend is adding us to this many groups. We worked around by modifying the SignalR client code and using a method for escaping url strings larger than 32K. Not a great solution, but works.

**Comment by moozzyk** [comment]
Glad you found workaround. I will close this issue for now as it is a known limitation of SignalR at the moment.
