### ISSUE TITLE
LostConnection – ObjectDisposedException

### ISSUE THREAD

**Issue by Chris369** [SignalR/SignalR#3696]
SignalR 2.2

Our client has Ping/Pong logic with the server that will call Stop on the SignalR connection. Is this some type of threading issue with Connection.Stop and LostConnection? 

Currently we are testing network issues using packet loss. One of our test clients crashed with this error logged in the event viewer…

Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
Stack:
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at Microsoft.AspNet.SignalR.Client.Transports.WebSocketTransport.LostConnection(Microsoft.AspNet.SignalR.Client.IConnection)
   at Microsoft.AspNet.SignalR.Client.Transports.AutoTransport.LostConnection(Microsoft.AspNet.SignalR.Client.IConnection)
   at Microsoft.AspNet.SignalR.Client.HeartbeatMonitor.CheckKeepAlive(System.TimeSpan)
   at Microsoft.AspNet.SignalR.Client.HeartbeatMonitor.Beat()
   at Microsoft.AspNet.SignalR.Client.HeartbeatMonitor.<Start>b__0(System.Object)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
