### ISSUE TITLE
Unexpected exception: /send. System.ArgumentNullException: Value cannot be null.  Parameter name: s

### ISSUE THREAD

**Issue by BoasE** [SignalR/SignalR#3697]
From time to time we have the following error in our log.

We are using LongPolling with SignalR.

I Created a logging middleware but I currently don't get more informationos then you can see below.

I found some posts about this error but most things were spongily.

We have high traffic on the site but only one per hour creates this error. So I assume there are ten thousands of requests which suceed until one fails :-/

Some times the accumulate and we have about 4,5 in 10 minutes. 

Currently we open the connection when the site is called and close it when the user leaves the site.

So I tried what happens when I close the windows while returning data but this doesn't create this error.

So I currently search any hint about this error and how to get more informations, about exact query string, browser and so on..

Any advice?

> Unexpected exception: /send.

```

System.ArgumentNullException: Value cannot be null.
 Parameter name: s
 at System.IO.StringReader..ctor(String s)
 at Microsoft.AspNet.SignalR.Json.JsonSerializerExtensions.Parse[T](JsonSerializer serializer, String json)
 at Microsoft.AspNet.SignalR.Hubs.HubRequestParser.Parse(String data, JsonSerializer serializer)
 at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.OnReceived(IRequest request, String connectionId, String data)
 at Microsoft.AspNet.SignalR.PersistentConnection.<>c__DisplayClassa.<>c__DisplayClassc.<ProcessRequestPostGroupRead>b__7()
 at Microsoft.AspNet.SignalR.TaskAsyncHelper.FromMethod(Func`1 func)
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.AspNet.SignalR.Transports.LongPollingTransport.<ProcessSendRequest>d__16.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Owin.Cors.CorsMiddleware.<Invoke>d__0.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Owin.Mapping.MapMiddleware.<Invoke>d__0.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Owin.Mapping.MapMiddleware.<Invoke>d__0.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

```

PS: I Also posted [here](http://stackoverflow.com/questions/37179435/signalr-2-2-0-how-to-get-mroe-details-error-value-cannot-be-null-parameter-s) if someone is hunting SO points.

Hope double posts are ok ?

**Comment by Gentlehag** [comment]
Any help ? this still occurs about 4 time a day :-/

**Comment by moozzyk** [comment]
Looks like this is the same as #3753 and #3374 and only happens with long polling transport.

**Comment by Perfekcjonista1618** [comment]
The problem occurs because instance of ur server been made BUT its GONE :D 
In Server part do this  WebApp.Start(serverAdress); OR you can assign it to IDisposable property and decide when to release memory.
Hope it help  someone, if it does LET ME KNOW my man :)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
