### ISSUE TITLE
Websocket connections fail in .net 4.6

### ISSUE THREAD

**Issue by richs99** [SignalR/SignalR#3699]
I have a signalr hub that worked beautifully with .net 4.5.

I have since upgraded the server to 4.6, but I now receive the following error:

System.InvalidOperationException: WebSockets is unsupported in the current application configuration. To enable this, set the following configuration switch in Web.config:
system.web
  httpRuntime targetFramework="4.5" 
system.web
For more information, see http://go.microsoft.com/fwlink/?LinkId=252465.
   at System.Web.Util.SynchronizationContextUtil.ValidateMode(SynchronizationContextMode currentMode, SynchronizationContextMode requiredMode, String specificErrorMessage)
   at System.Web.HttpContext.AcceptWebSocketRequest(Func`2 userFunc, AspNetWebSocketOptions options)
   at Microsoft.AspNet.SignalR.Transports.WebSocketTransport.AcceptWebSocketRequest(Func`2 callback)
   at Microsoft.AspNet.SignalR.PersistentConnection.ProcessRequestPostGroupRead(HostContext context, String groupsToken)
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.FromMethod[T1,T2,T3,TResult](Func`4 func, T1 arg1, T2 arg2, T3 arg3)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Mapping.MapMiddleware.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

While adding the HTTPRuntime line does fix the problem, it introduces a whole bunch of other major issues to my site that I can't resolve.

Is there a plan to get signalr websockets working with 4.6?

**Comment by davidfowl** [comment]
> While adding the HTTPRuntime line does fix the problem, it introduces a whole bunch of other major issues to my site that I can't resolve.

What issues?

**Comment by richs99** [comment]
> What issues?

the machine key stops working the second we add an httpruntime element, and we have high traffic sites on a web farm. This causes (literally) thousands of viewstate errors an hour. 

After spending over a week trying to fix the viewstate issues, the only thing we found that worked was to remove the httpruntime element from the web.config, the moment we did this the viewstate errors stopped.

**Comment by IanYates** [comment]
Is this your issue?
https://blogs.msdn.microsoft.com/webdev/2014/09/09/farewell-enableviewstatemac/

**Comment by Gita111** [comment]
I am seeing exactly the same problem.
Any ideas how to solve it?

**Comment by moozzyk** [comment]
I am not able to repro this. I created a sample chat app and after I turned on webSockets in IIS settings I can see that the SignalR is using webSockets transport. The web.config file had this line by default: 
```
  <httpRuntime targetFramework="4.6" />
```
and I did not change it. Please provide a repro or details allowing to reproduce the issue.

**Comment by moozzyk** [comment]
No follow up - closing.

**Comment by lextm** [comment]
@moozzyk Developers should be able to reproduce this exception by setting `<httpRuntime targetFramework="4.0" />`. The compatibility mode disables WebSockets and throws that exception.

@richs99 in your case you should set `<httpRuntime targetFramework="4.6" />` to match the actual project target framework version, not 4.5.

@Gita111 you probably hit the same issue so should revise `httpRuntime` tag accordingly.
