### ISSUE TITLE
System.ObjectDisposedExceptionThe CancellationTokenSource has been disposed 

### ISSUE THREAD

**Issue by akramhaddaji** [SignalR/SignalR#3722]
Hi,
I still got ObjectDisposedException and application crash with 2.1.2 SignalR version.
Here is the stacktrace: 

System.Threading.CancellationTokenSource.InternalRegister(Action<_> callback, object stateForCallback, SynchronizationContext targetSyncContext, ExecutionContext executionContext)
System.Threading.CancellationToken.Register(Action<_> callback, object state, bool useSynchronizationContext, bool useExecutionContext)
System.Threading.CancellationToken.Register(Action<_> callback, object state)
Microsoft.AspNet.SignalR.Infrastructure.CancellationTokenExtensions.<ResolveRegisterDelegate>b__4(ref CancellationToken token, Action<_> callback, object state)
at (wrapper delegate-invoke) <Module>:invoke_CancellationTokenRegistration_CancellationToken&_Action`1<object>_object (System.Threading.CancellationToken&,System.Action`1<object>,object)
Microsoft.AspNet.SignalR.Infrastructure.CancellationTokenExtensions.SafeRegister(CancellationToken cancellationToken, Action<_> callback, object state)
Microsoft.AspNet.SignalR.Client.Transports.ServerSentEventsTransport.OpenConnection(IConnection connection, string data, CancellationToken disconnectToken, Action initializeCallback, Action<_> errorCallback)
Microsoft.AspNet.SignalR.Client.Transports.ServerSentEventsTransport.<>c__DisplayClass2.<Reconnect>b__1()
Microsoft.AspNet.SignalR.TaskAsyncHelper.<>c__DisplayClass2e.<RunTask>b__2d(Task t)

Any help is appreciated.

**Comment by TingtingAn** [comment]
Hi @akramhaddaji , did you fix this issue? I am hitting it.

**Comment by jinek** [comment]
Same in 2.3.0:

```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.ObjectDisposedException: The CancellationTokenSource has been disposed.
at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
at System.Threading.CancellationTokenSource.InternalRegister(Action`1 callback, Object stateForCallback, SynchronizationContext targetSyncContext, ExecutionContext executionContext)
at System.Threading.CancellationToken.Register(Action`1 callback, Object state, Boolean useSynchronizationContext, Boolean useExecutionContext)
at System.Threading.CancellationToken.InternalRegisterWithoutEC(Action`1 callback, Object state)
at Microsoft.AspNet.SignalR.Infrastructure.CancellationTokenExtensions.SafeRegister(CancellationToken cancellationToken, Action`1 callback, Object state)
at Microsoft.AspNet.SignalR.Client.Infrastructure.TransportInitializationHandler..ctor(IHttpClient httpClient, IConnection connection, String connectionData, String transport, CancellationToken disconnectToken, TransportHelper transportHelper)
at Microsoft.AspNet.SignalR.Client.Transports.ClientTransportBase.Start(IConnection connection, String connectionData, CancellationToken disconnectToken)
at Microsoft.AspNet.SignalR.Client.Transports.AutoTransport.ResolveTransport(IConnection connection, String data, CancellationToken disconnectToken, DispatchingTaskCompletionSource`1 tcs, Int32 index)
at Microsoft.AspNet.SignalR.Client.Transports.AutoTransport.<>c_DisplayClass13_0.<ResolveTransport>b_0(Task task)
at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
at System.Threading.Tasks.Task.Execute()
— End of inner exception stack trace —
---> (Inner Exception #0) System.ObjectDisposedException: The CancellationTokenSource has been disposed.
```

**Comment by anurse** [comment]
Can you provide a code sample that illustrates the issue? I'm not seeing this in normal operation so I need to understand a bit better what you're doing to trigger the exception.

**Comment by jinek** [comment]
I don't know conditions either, just got it in error log. But from exception it seems there is a "async void" code, that trying to do something with disposed CancellationTokenSource. I supposed it can be reproduced by submitting to TaskScheduler.UnobservedTaskException, running a connection from client and do something with connection, like interrupting it. May be it can happened during AppDomain unloading (during switching off application). Or may be it can be reproduced by AppDomain unloading during interrupted connection. I'm thinking about AppDomain unloading because If this CancellationTokenSource was disposed and from the code it is not evident thing, may be it was disposed by finalizer?

**Comment by anurse** [comment]
Ok, so this is only triggering on your `TaskScheduler.UnobservedTaskException` handler? Or is it actually crashing the process?

This can be caused by an inherent race between `Start` (or a reconnect) and `Disconnect`. The call to `Disconnect` disposes the token so if there's a connection attempt underway this exception is expected to occur. If it's just triggering your `UnobservedTaskException` handler you can safely filter it out unless you're seeing other problems that might be caused by this issue.

We only ever Dispose the CTS after cancelling it, so it's safe to ignore the exception.

**Comment by jinek** [comment]
> Or is it actually crashing the process?
In my case unhandled exceptions can not crash the process (unless Stackoverflow etc), but all considered as an issue. Process termination depends on application policy: https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskscheduler.unobservedtaskexception?view=netframework-4.7.2
In some frameworks it will be terminated by default, in some no.

That is good news we can ignore it. But the problem is we can't distinguish this error from others. We can't understand if this exception happened because of this case or another one. Currently I use this workaround:

```
static SignalRBugWorkAround()
        {
            ExceptionManager.UnobservedTaskException += (sender, args) =>
            {
                if (args.Observed) return;
                
                var exception = args.Exception;

                if (!(exception.InnerException is ObjectDisposedException)) return;
                
                if(exception.StackTrace.ToUpper().Contains(@"System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
at System.Threading.CancellationTokenSource.InternalRegister(Action`1 callback, Object stateForCallback, SynchronizationContext targetSyncContext, ExecutionContext executionContext)
at System.Threading.CancellationToken.Register(Action`1 callback, Object state, Boolean useSynchronizationContext, Boolean useExecutionContext)
at System.Threading.CancellationToken.InternalRegisterWithoutEC(Action`1 callback, Object state)
at Microsoft.AspNet.SignalR.Infrastructure.CancellationTokenExtensions.SafeRegister(CancellationToken cancellationToken, Action`1 callback, Object state)
at Microsoft.AspNet.SignalR.Client.Infrastructure.TransportInitializationHandler..ctor(IHttpClient httpClient, IConnection connection, String connectionData, String transport, CancellationToken disconnectToken, TransportHelper transportHelper)
at Microsoft.AspNet.SignalR.Client.Transports.ClientTransportBase.Start(IConnection connection, String connectionData, CancellationToken disconnectToken)
at Microsoft.AspNet.SignalR.Client.Transports.AutoTransport.ResolveTransport(IConnection connection, String data, CancellationToken disconnectToken, DispatchingTaskCompletionSource`1 tcs, Int32 index)
at Microsoft.AspNet.SignalR.Client.Transports.AutoTransport.<>c_DisplayClass13_0.<ResolveTransport>b_0(Task task)
at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()".ToUpper()))
                    args.SetObserved();
            };
        } 
```

Of course it will be broken on next SignalR update) . May be it does make sense to rethrow another type of exception, or catch this exception at exact place where it is thrown? Or may be to make some synchronization to ensure token was not disposed?

**Comment by anurse** [comment]
I think we can reasonably catch this exception. I'll look in to doing that.
