### ISSUE TITLE
>.net client calling wrong SignalR proxy makes Hub (Server) throwing continues exceptions .

### ISSUE THREAD

**Issue by charithsoori** [SignalR/SignalR#3777]
### Call Signalr server (hub) pointing to a wrong Signalr hub name

Error stack
System.InvalidOperationException: 'SignalRHub' Hub could not be resolved.
[9/22/2016 5:15:12 PM] Janitha Tennakoon: FATAL  An unhandled application error exception occured (PrintCloud.Web.Global.Application_Error) System.InvalidOperationException: 'SignalRHub' Hub could not be resolved.
   at Microsoft.AspNet.SignalR.Hubs.HubManagerExtensions.EnsureHub(IHubManager hubManager, String hubName, IPerformanceCounter[] counters)
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.AuthorizeRequest(IRequest request)
   at Microsoft.AspNet.SignalR.PersistentConnection.ProcessRequest(IDictionary`2 environment)
   at Microsoft.Owin.Mapping.MapMiddleware.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) | PipelineStepManager.ResumeSteps => HttpApplication.RaiseOnError

**Comment by moozzyk** [comment]
Each request sent to the server contain a list of hubs. If the hub sent by the client cannot be resolved the server will throw. This is by design. 
Is there any scenario where you would want to try to use a hub that don't exist and consider it a valid usage?

**Comment by charithsoori** [comment]
In our scenario, a name change of hub leads to this situation . I think this is  a possible scenario since clients are in distributed environments . It is acceptable if the server (hub) throws 1 error but not continues or this error thrown from clients . 
We want the hub to run 100% up when issue or errors made from the client side .
