### ISSUE TITLE
Backplane SQL notification issue with TableCount greater than default value

### ISSUE THREAD

**Issue by nettrax** [SignalR/SignalR#3808]
Our environment is composed of 3 web servers and a sql server. Signalr (v2.2.1) is configured with TableCount=3 on all web servers (same behavior with TableCount=2).

### Expected behavior
Systematically, SQL notification change is fired quickly after saving payload. Log sample :

```
SignalR.SqlMessageBus Verbose: 0 : Stream 1 : Saving payload with 1 messages(s) to SQL server
    DateTime=2016-11-08T22:00:49.4359959Z
SignalR.SqlMessageBus Information: 0 : Stream 1 : SQL notification change fired
    DateTime=2016-11-08T22:00:49.4670004Z
SignalR.SqlMessageBus Verbose: 0 : Stream 1 : SQL notification details: Type=Change, Source=Data, Info=Update
    DateTime=2016-11-08T22:00:49.4715759Z
```

### Actual behavior
Most of the time, Sql notification change is fired quickly (about 10 ms). But, randomly, sql notification change is fired 10-20 seconds after saving payload. I have extracted a piece of signalr log showing this behavior.
After saving payload to SQL server on Stream 2 (2016-11-08T16:39:37.7892338Z), sql notification change takes 10  seconds to be fired (2016-11-08T16:39:49.3964484Z).

```
SignalR.SqlMessageBus Verbose: 0 : Stream 2 : Saving payload with 1 messages(s) to SQL server
    DateTime=2016-11-08T16:39:37.7892338Z
SignalR.SqlMessageBus Verbose: 0 : Created DbCommand: CommandType=Text, CommandText=SELECT [PayloadId], [Payload], [InsertedOn] FROM [SignalR].[Messages_1] WHERE [PayloadId] > @PayloadId, Parameters= [Name=PayloadId, Value=55212194]
    DateTime=2016-11-08T16:39:38.2884738Z
SignalR.SqlMessageBus Verbose: 0 : Stream 1 : No records received
    DateTime=2016-11-08T16:39:38.2884738Z
SignalR.SqlMessageBus Verbose: 0 : Stream 1 : Waiting 1000ms before checking for messages again
    DateTime=2016-11-08T16:39:38.2884738Z
SignalR.SqlMessageBus Verbose: 0 : Created DbCommand: CommandType=Text, CommandText=SELECT [PayloadId], [Payload], [InsertedOn] FROM [SignalR].[Messages_1] WHERE [PayloadId] > @PayloadId, Parameters= [Name=PayloadId, Value=55212194]
    DateTime=2016-11-08T16:39:39.3025405Z
SignalR.SqlMessageBus Verbose: 0 : Stream 1 : No records received
    DateTime=2016-11-08T16:39:39.3025405Z
SignalR.SqlMessageBus Verbose: 0 : Stream 1 : Waiting 1500ms before checking for messages again
    DateTime=2016-11-08T16:39:39.3025405Z
SignalR.SqlMessageBus Verbose: 0 : Created DbCommand: CommandType=Text, CommandText=SELECT [PayloadId], [Payload], [InsertedOn] FROM [SignalR].[Messages_0] WHERE [PayloadId] > @PayloadId, Parameters= [Name=PayloadId, Value=448815951]
    DateTime=2016-11-08T16:39:40.4726218Z
SignalR.SqlMessageBus Verbose: 0 : Stream 0 : No records received
    DateTime=2016-11-08T16:39:40.4726218Z
SignalR.SqlMessageBus Verbose: 0 : Stream 0 : Setting up SQL notification
    DateTime=2016-11-08T16:39:40.4726218Z
SignalR.SqlMessageBus Verbose: 0 : Created DbCommand: CommandType=Text, CommandText=SELECT [PayloadId], [Payload], [InsertedOn] FROM [SignalR].[Messages_0] WHERE [PayloadId] > @PayloadId, Parameters= [Name=PayloadId, Value=448815951]
    DateTime=2016-11-08T16:39:40.4726218Z
SignalR.SqlMessageBus Verbose: 0 : Stream 0 : No records received while setting up SQL notification
    DateTime=2016-11-08T16:39:40.4726218Z
SignalR.SqlMessageBus Verbose: 0 : Stream 0 : Receive loop exiting
    DateTime=2016-11-08T16:39:40.4726218Z
SignalR.SqlMessageBus Verbose: 0 : Created DbCommand: CommandType=Text, CommandText=SELECT [PayloadId], [Payload], [InsertedOn] FROM [SignalR].[Messages_1] WHERE [PayloadId] > @PayloadId, Parameters= [Name=PayloadId, Value=55212194]
    DateTime=2016-11-08T16:39:40.8158397Z
SignalR.SqlMessageBus Verbose: 0 : Stream 1 : No records received
    DateTime=2016-11-08T16:39:40.8158397Z
SignalR.SqlMessageBus Verbose: 0 : Stream 1 : Waiting 1500ms before checking for messages again
    DateTime=2016-11-08T16:39:40.8158397Z
SignalR.SqlMessageBus Verbose: 0 : Created DbCommand: CommandType=Text, CommandText=SELECT [PayloadId], [Payload], [InsertedOn] FROM [SignalR].[Messages_1] WHERE [PayloadId] > @PayloadId, Parameters= [Name=PayloadId, Value=55212194]
    DateTime=2016-11-08T16:39:42.3291538Z
SignalR.SqlMessageBus Verbose: 0 : Stream 1 : No records received
    DateTime=2016-11-08T16:39:42.3291538Z
SignalR.SqlMessageBus Verbose: 0 : Stream 1 : Waiting 3000ms before checking for messages again
    DateTime=2016-11-08T16:39:42.3291538Z
SignalR.SqlMessageBus Verbose: 0 : Created DbCommand: CommandType=Text, CommandText=SELECT [PayloadId], [Payload], [InsertedOn] FROM [SignalR].[Messages_1] WHERE [PayloadId] > @PayloadId, Parameters= [Name=PayloadId, Value=55212194]
    DateTime=2016-11-08T16:39:45.3401550Z
SignalR.SqlMessageBus Verbose: 0 : Stream 1 : No records received
    DateTime=2016-11-08T16:39:45.3401550Z
SignalR.SqlMessageBus Verbose: 0 : Stream 1 : Setting up SQL notification
    DateTime=2016-11-08T16:39:45.3401550Z
SignalR.SqlMessageBus Verbose: 0 : Created DbCommand: CommandType=Text, CommandText=SELECT [PayloadId], [Payload], [InsertedOn] FROM [SignalR].[Messages_1] WHERE [PayloadId] > @PayloadId, Parameters= [Name=PayloadId, Value=55212194]
    DateTime=2016-11-08T16:39:45.3401550Z
SignalR.SqlMessageBus Verbose: 0 : Stream 1 : No records received while setting up SQL notification
    DateTime=2016-11-08T16:39:45.3401550Z
SignalR.SqlMessageBus Verbose: 0 : Stream 1 : Receive loop exiting
    DateTime=2016-11-08T16:39:45.3401550Z
SignalR.SqlMessageBus Information: 0 : Stream 2 : SQL notification change fired
    DateTime=2016-11-08T16:39:49.3964484Z
SignalR.SqlMessageBus Verbose: 0 : Stream 2 : SQL notification details: Type=Change, Source=Data, Info=Update
    DateTime=2016-11-08T16:39:49.3964484Z
SignalR.SqlMessageBus Information: 0 : Stream 2 : Starting receive loop again to process updates
    DateTime=2016-11-08T16:39:49.3964484Z
SignalR.SqlMessageBus Verbose: 0 : Stream 2 : Starting SQL notification listener
```

Have you got a idea explaining this issue ?

**Comment by AndyBullivent** [comment]
Hi, I'm having a similar issue I think. The symptoms for me are that if I start the MVC web app I have using signalr, with a single table, all connections from the js client via websockets are virtually instantaneous. If I up the tablecount, the start up behaviour is far more volatile. Connecting 60% of the time fine, but the other 40% it will hang on attempting the web sockets connection, fail over to SSE/Longpolling, and then will mostly timeout and fail. This is on a 2 server system using SQL server 2012. Service Broker is on for the backplane and I'm seeing no errors in the tracing, just the JS client.
using SignalR v2.2.2, OWIN, dependency injection with latest NINJECT and EF 6. Any thoughts?

**Comment by AndyBullivent** [comment]
Ok, perhaps not - looking at the scaleout trace logs, I get the following if tablecount is not 1:

```
OnError(3ce05bbb-d8eb-4ff9-bf94-8d094a8ed8df, System.Net.WebSockets.WebSocketException (0x80070040): The specified network name is no longer available
   at System.Web.WebSockets.WebSocketPipe.<>c__DisplayClass7.<ReadFragmentAsync>b__6(Int32 hrError, Int32 cbIO, Boolean fUtf8Encoded, Boolean fFinalFragment, Boolean fClose)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.WebSockets.AspNetWebSocket.<DoWork>d__2d`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.WebSockets.AspNetWebSocket.<>c__DisplayClass1a.<<ReceiveAsyncImpl>b__18>d__1c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.WebSockets.WebSocketMessageReader.<ReadMessageAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.WebSockets.WebSocketHandler.<ProcessWebSocketRequestAsync>d__25.MoveNext())
```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Comment by ajbeaven** [comment]
@nettrax did you ever figure out what the issue was?

I'm running using the default TableCount and am still occasionally experiencing a 30+ second delay between when the payload is added to the database and when the SQL notification is fired.

**Comment by nettrax** [comment]
@ajbeaven 
I have stopped using sql notification (disable service broker for the backplane database). 
The polling strategy of signalr was sufficient to my project.
I have increased TableCount to 60 to reduce locks (dispatching writes and reads in many tables) in signalr backplane.
