### ISSUE TITLE
ServiceBus Scaleout: MessagingEntityNotFoundException on topic subscription

### ISSUE THREAD

**Issue by anpau** [SignalR/SignalR#3824]
For approximately a 10-15 second period, we saw the following exception when trying to publish messages in our production SignalR deployment using ServiceBus scale-out. Before and after that time period, notifications were sent without problems.

It appears that a subscription was deleted, as the topic subscription endpoint could not be found. Should SignalR be handling this exception so as to not throw and prevent the message from being sent? I noticed that SignalR uses an idle subscription timeout and that could be the culprit here.

### Expected  behavior
SignalR message can be sent using ServiceBus scale-out.

### Actual behavior
Type: Microsoft.ServiceBus.Messaging.MessagingEntityNotFoundException
Message: 40400: Endpoint not found., Resource:sb://{removed}.servicebus.windows.net/signalr_topic_notificationservice_3/subscriptions/c79d7aaf-8439-4c33-bfc8-e3bb4e29f299. TrackingId:be1dde77-0eb1-423e-8e26-d90b7a7b1663_G16, SystemTracker:{removed}.servicebus.windows.net:SIGNALR_TOPIC_NotificationService_3/Subscriptions/c79d7aaf-8439-4c33-bfc8-e3bb4e29f299, Timestamp:11/29/2016 6:31:07 PM
ToString: 40400: Endpoint not found., Resource:sb://{removed}.servicebus.windows.net/signalr_topic_notificationservice_3/subscriptions/c79d7aaf-8439-4c33-bfc8-e3bb4e29f299. TrackingId:be1dde77-0eb1-423e-8e26-d90b7a7b1663_G16, SystemTracker:{removed}.servicebus.windows.net:SIGNALR_TOPIC_NotificationService_3/Subscriptions/c79d7aaf-8439-4c33-bfc8-e3bb4e29f299, Timestamp:11/29/2016 6:31:07 PM
StackTrace:
    at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func`2 send, Object state)
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.SendImpl(IEnumerator`1 enumerator, TaskCompletionSource`1 taskCompletionSource)
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.Send(IList`1 messages)
   at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message)
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Outgoing(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass6_0.<BuildOutgoing>b__0(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass6_0.<BuildOutgoing>b__0(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass6_0.<BuildOutgoing>b__0(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass6_0.<BuildOutgoing>b__0(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipeline.Send(IHubOutgoingInvokerContext context)
   at

**Comment by moozzyk** [comment]
What version of ServiceBus have you tried to use? 
This might this: https://github.com/SignalR/SignalR/issues/2596

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
