### ISSUE TITLE
SQL backplane causes The wait operation timed out exception

### ISSUE THREAD

**Issue by janitha000** [SignalR/SignalR#3923]
We have recently implemented the backplane using sql server. The server that we created the backplane contains other databases as well. These other databases are accessed by different applications which are on different servers. For stress testing we implemented a simple signalr client program which sends a message to the server every 30 seconds. There are two servers which are handled by a load balancer. The backplane works perfectly when number of clients are small. 

The issue is when the number of clients are higher. (closer to 50 or more). The following exception is thrown by other applications that tries to use the database server for a different database. 

```
System.Data.SqlClient.SqlException: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception: The wait operation timed out
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   --- End of inner exception stack trace ---
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
```
Because of this exception all the other applications breaks since they can not access the database. The problem immidiately fixes if we disable the backplane. (stopping the two signalr servers)

**Comment by moozzyk** [comment]
Where it is being thrown from? I don't see SignalR on the stack...

**Comment by janitha000** [comment]
It is thrown from any other application which access the same database server where backplane resides, not from the signalr server. If we stop the backplane then those applications are available to query the database. Also we noticed that most of those applications have more than 1000 threads running in their IIS instance when this occurs.

**Comment by janitha000** [comment]
We also found out that the when throwing this exception the machine has allocated more that 1000 threads for w3wp.exe process and is increasing (went for more than 6000 in one occasion). When we looked in to the worker processes they all seemed to be signalr connections. 

![capture2](https://cloud.githubusercontent.com/assets/5737103/25701301/6e6cb918-30e9-11e7-903c-c40f28c53abf.PNG)

![capture](https://cloud.githubusercontent.com/assets/5737103/25700993/de625ee6-30e7-11e7-91a7-51b286a83392.PNG)

**Comment by moozzyk** [comment]
I have not seen a report similar to this so can't tell what's going on. You need to figure out what is happening with SqlServer.   think the "connect" requests might be trying to execute a command/query in the database but since Sql Server is blocked/clogged they wait for their turn. I would start investigating from looking how much CPU Sql Server is using and what query causes it. Then I would look at deadlocks etc.

**Comment by janitha000** [comment]
We did a profile in the sql server machine but found that CPU and memory usages are pretty normal. (around 2-10% CPU and 25% memory on 6GB). But what we noticed when running SQL server profiler is that suddenly the signalr server stops querying from the database without any specific reason. (we looked in to the event viewer as well, but could not find anything).  Because of that for all the signalr clients requests for connect request IIS creates worker process. Any idea why server stops accessing backplane database?

**Comment by janitha000** [comment]
Also noticed that in SQL server profiler for the server some connections show more than 10 minutes for Audit Logout event, which means that the sql connection is opened for more than 10 minutes. Further investigation could not find any deadlocks or locks wait.

**Comment by moozzyk** [comment]
What SqlServer edition are you using? If this affect entire Sql Server maybe you are hitting some built-in limits...

**Comment by janitha000** [comment]
We are using SQL Server 2012, we tried in two machines where both sowed the same problem.

**Comment by janitha000** [comment]
Closing issue due to moving the issue to [here](https://github.com/SignalR/SignalR/issues/3941)
