### ISSUE TITLE
Some properties of HttpRequestBase throw errors in onDisconnect(false) 

### ISSUE THREAD

**Issue by cwtowns77** [SignalR/SignalR#3980]
When a client disconnects abnormally and onDisconnect is called with false, certain properties of the HttpRequest will throw an error if inspected.  For example, in onDisconnected I have the following:

Context.Request.GetHttpContext().Request.IsSecureConnection

If I launch my browser, connect to the sample chat app, and then end task the browser, once the connection times out out on the server the following exception is generated: 

   Value does not fall within the expected range.

   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Web.Hosting.IIS7WorkerRequest.GetServerVariableInternal(String name)
   at System.Web.Hosting.IIS7WorkerRequest.GetServerVariable(String name)
   at System.Web.Hosting.IIS7WorkerRequest.IsSecure()
   at System.Web.HttpRequestWrapper.get_IsSecureConnection()

Inspecting the request object on the http context shows the following additional properties generating errors:

    ClientCertificate
    HttpChannelBinding
    IsLocal
    IsSecureConection
    LogonUserIdentity
    Params
    TimedOutToken
    TlsTokenBindingInfo
    UserHostAddress
    UserHostName

**Comment by moozzyk** [comment]
When a connection times out there is no active request,
