### ISSUE TITLE
SignalR Scaleout Redis cluster master/slave issue

### ISSUE THREAD

**Issue by msinha53** [SignalR/SignalR#4002]
We are running a SignalR in API service on IIS servers .The problem is occurred in SignalR Scaleout backplane tries to write to a slave on the Redis cluster. Once this exception occurs it never goes away. We have to restart the windows service to force a reconnect to the Redis cluster. The restart solves the problem.
We are using SignalR 2.2.2.
Call Stack:
stack:UTC:2017-08-18 13:44:29,693 [72] ERROR StackExchange.Redis.RedisServerException: ERR Error running script (call to f_5b8e3b60e050400311bc8b6ef2cbba37bc0b9cb3): @user_script:1: @user_script: 1: -READONLY You can't write against a read only slave.
 at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func`2 send, Object state)
 at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message)
 at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Outgoing(IHubOutgoingInvokerContext context)
 at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass6_0.b__0(IHubOutgoingInvokerContext context)
 at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass6_0.b__0(IHubOutgoingInvokerContext context)
 at Microsoft.AspNet.SignalR.Hubs.SignalProxy.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
 at CallSite.Target(Closure , CallSite , Object , RealTimeData , RtsRealTimeSubscription )
 at ChannelHub.Notify(RealTimeDataEx realTimeDataEx) in

**Comment by moozzyk** [comment]
As per https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/scaleout-with-redis Redis clusters are not supported.
