### ISSUE TITLE
Update NuGet dependencies (for example Newtonsoft.Json)

### ISSUE THREAD

**Issue by MagicAndre1981** [SignalR/SignalR#4110]
### Expected  behavior

All NuGet dependencies (for example Newtonsoft.Json) are up to date

### Actual behavior

SignalR uses 4 years [old version 6.0.4](https://www.nuget.org/packages/Newtonsoft.Json/6.0.4)

### Solution:

always update the NuGet dependencies and release a minor update (Semantic Versioning) which includes the updated NuGet dependencies to make sure that user use the latest nuget versions in the applications.

**Comment by anurse** [comment]
Are you seeing an issue when you update your version of Newtonsoft.Json to a higher version? SignalR doesn't require `6.0.4`, it sets a **minimum** version of `6.0.4`, you're always welcome to update to a higher version in your project.

To be clear, I'm not disagreeing that updating would be a good idea, I'm just trying to understand if you're seeing a bug.

**Comment by anurse** [comment]
> I get errors in debug Window of VS2017 that the older version was not found

This isn't the first time I've heard of this. We should dig deeper here because it should work with redirects. Can you post an example application including the `app.config`? Or, perhaps share portions of your current application? I'd like to get to the bottom of this since Binding Redirects are supposed to handle this problem.

**Comment by MagicAndre1981** [comment]
For what ever reason it has now gone.

The only thing I can say is I have a Xamarin.Forms project, using .net standard 2.0 as shared project for the UWP/Android solution so I have a new cs formatted .net standard file and old csproj format for both xamarin projects. maybe this has a something to do with it.

**Comment by anurse** [comment]
Hrm, that shouldn't cause a problem. I'm going to leave this open since we may consider increasing the minimum version here.

**Comment by MagicAndre1981** [comment]
ok, please enable SourceLink and bump min Version of Json.net to 11.3 (when this version gets released), to improve debugging experience.

**Comment by anurse** [comment]
> please enable SourceLink

Yep, your other issue is tracking this #4109 

> bump min Version of Json.net to 11.3

Can you explain how this helps your debugging experience? Increasing the minimum version can have compatibility issues, since it forces all consumers of SignalR to upgrade. Leaving the minimum version allows consumers to decide if they want to upgrade, so I'm trying to understand what the improvement is here. You can always update the package in your own project to override the version SignalR uses with the higher version and get SourceLink support in Newtonsoft.Json regardless of what version we depend upon. Is that not working in your scenario?

**Comment by JeffSBailey** [comment]
For what it is worth, unless a user of the signalr nuget package overrides it, the package is vulnerable to the high severity WS-2022-0161 because of it's use of an OLD version of Newtonsoft.

**Comment by Saltallica** [comment]
An ancient version at this point. I am stumbling into an issue where my projects are using version 13 for various things, with redirects in place. I also have to dynamically load assemblies that use Newtonsoft.json 13.0.0 and the Microsoft.AspNet.SignalR.Core 2.4.3 package that is using 6.0.0. Due to assembly binding madness, it appears that I end up with with MissingMethod exceptions when combined with self hosting package:

```
An exception of type 'System.Reflection.TargetInvocationException' occurred and was caught.

Main Exception:
Type: System.Reflection.TargetInvocationException
Source: mscorlib
Message: Exception has been thrown by the target of an invocation.
HelpLink: 
StackTrace:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Owin.Loader.DefaultLoader.<>c__DisplayClass19_1.<MakeDelegate>b__0(IAppBuilder builder) in /_/src/Owin.Loader/DefaultLoader.cs:line 429
   at Owin.Loader.DefaultLoader.<>c__DisplayClass9_0.<LoadImplementation>b__0(IAppBuilder builder) in /_/src/Owin.Loader/DefaultLoader.cs:line 127
   at Microsoft.Owin.Hosting.Engine.HostingEngine.ResolveApp(StartContext context) in /_/src/Microsoft.Owin.Hosting/Engine/HostingEngine.cs:line 410
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context) in /_/src/Microsoft.Owin.Hosting/Engine/HostingEngine.cs:line 98
   at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options) in /_/src/Microsoft.Owin.Hosting/Starter/DirectHostingStarter.cs:line 32
   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options) in /_/src/Microsoft.Owin.Hosting/Starter/HostingStarter.cs:line 42
   at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options) in /_/src/Microsoft.Owin.Hosting/WebApp.cs:line 121
   at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options) in /_/src/Microsoft.Owin.Hosting/WebApp.cs:line 84
   at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options) in /_/src/Microsoft.Owin.Hosting/WebApp.cs:line 60
   at Forte.AD.Agents.Interface.RestWMSInterface.RestSynQWmsInterface.Run()
TargetSite: InvokeMethod

Inner Exception:
Type: System.MissingMethodException
Source: Forte.AD.Agents.Interface
Message: Method not found: 'Newtonsoft.Json.JsonSerializerSettings System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.get_SerializerSettings()'.
HelpLink: 
StackTrace:    at Forte.AD.Agents.Interface.RestWMSInterface.WebHostStartup.Configuration(IAppBuilder app)
TargetSite: Configuration
```

When I run this same OWIN startup class in a unit test without any dynamic assembly loading, every thing starts up just fine. Same versions of packages, same assembly binding redirects.  I used the wonderful Fusion++ to review the fusion logs to see if version 6.0.0 was sneaking in somewhere, and all the logs state the redirect was working. 

I'm pulling my hair out.

**Comment by GMacAussie** [comment]
@Saltallica 

Hmm not sure if I am going to be helping here, but I figure knowing somebody else's package setup may give a clue. This is from our web.config:

```
  <dependentAssembly>
    <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-13.0.0.0" newVersion="13.0.0.0" />
  </dependentAssembly>

  <dependentAssembly>
    <assemblyIdentity name="Microsoft.Owin.Security" publicKeyToken="31bf3856ad364e35" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-4.2.2.0" newVersion="4.2.2.0" />
  </dependentAssembly>
  <dependentAssembly>
    <assemblyIdentity name="Microsoft.Owin" publicKeyToken="31bf3856ad364e35" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-4.2.2.0" newVersion="4.2.2.0" />
  </dependentAssembly>

  <dependentAssembly>
    <assemblyIdentity name="Microsoft.AspNet.SignalR.Core" publicKeyToken="31bf3856ad364e35" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-2.4.3.0" newVersion="2.4.3.0" />
  </dependentAssembly>
```

And package.json:

```
  <package id="Newtonsoft.Json" version="13.0.3" targetFramework="net48" />

  <package id="Owin" version="1.0" targetFramework="net48" />
  <package id="Microsoft.Owin" version="4.2.2" targetFramework="net48" />
  <package id="Microsoft.Owin.Cors" version="4.2.2" targetFramework="net48" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="4.2.2" targetFramework="net48" />
  <package id="Microsoft.Owin.Security" version="4.2.2" targetFramework="net48" />
  <package id="Microsoft.Owin.Security.Jwt" version="4.2.2" targetFramework="net48" />
  <package id="Microsoft.Owin.Security.OAuth" version="4.2.2" targetFramework="net48" />
  <package id="Microsoft.Owin.Security.OpenIdConnect" version="4.2.2" targetFramework="net48" />

  <package id="Microsoft.AspNet.SignalR" version="2.4.3" targetFramework="net48" />
  <package id="Microsoft.AspNet.SignalR.Core" version="2.4.3" targetFramework="net48" />
  <package id="Microsoft.AspNet.SignalR.JS" version="2.4.3" targetFramework="net48" />
  <package id="Microsoft.AspNet.SignalR.Owin" version="1.2.2" targetFramework="net48" />
  <package id="Microsoft.AspNet.SignalR.StackExchangeRedis" version="2.4.3" targetFramework="net48" />
  <package id="Microsoft.AspNet.SignalR.SystemWeb" version="2.4.3" targetFramework="net48" />
```

Let me know if there is some other config info you might like. Sorry cannot be more help.

Cheers,
Graham
