### ISSUE TITLE
Random crash when logging is enabled

### ISSUE THREAD

**Issue by maithanhtan** [SignalR/SignalR#4146]
# Issues related to the Asp.NET Core version of SignalR should be filed in the corresponding SignalR repo: https://github.com/aspnet/?utf8=%E2%9C%93&query=Signalr

### Expected  behavior
SignalR should handle these exception and don't made app crash
### Actual behavior
SignalR.Transports.TransportHeartBeat Error: 0 : SignalR error during transport heart beat on background thread: System.ArgumentOutOfRangeException: Count cannot be less than zero.
Parameter name: count
   at System.String.CopyTo(Int32 sourceIndex, Char[] destination, Int32 destinationIndex, Int32 count)
   at System.IO.StreamWriter.Write(String value)
   at System.IO.TextWriter.SyncTextWriter.Write(String value)
   at Microsoft.Owin.Hosting.Tracing.DualWriter.Write(String value)
   at System.Diagnostics.TextWriterTraceListener.Write(String message)
   at System.Diagnostics.TraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at System.Diagnostics.TraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at Microsoft.AspNet.SignalR.Transports.TransportHeartbeat.Beat(Object state)
### Steps to reproduce
Start Server with logging enabled.
Connect some client to server
Keep it running for about 15 - 30 min then get crash
[transports.log.txt](https://github.com/SignalR/SignalR/files/2168785/transports.log.txt)

**Comment by anurse** [comment]
This is a well-known issue here with the `DualWriter` component. It should only reproduce when `Console.Out` and `Console.Error` are pointing to the same stream though (which can happen when the VS Debugger is attached but should not happen in general use). Are you seeing this issue outside of the debugger?

See https://github.com/aspnet/AspNetKatana/issues/54 for more detail.

**Comment by maithanhtan** [comment]
@anurse Yes, I see this issue when running outside of debugger.
Currently i turn off log from SignalR and this issue wont happen on my production

**Comment by anurse** [comment]
@maithanhtan That's definitely useful information. Can you report this on the linked issue in AspNetKatana (https://github.com/aspnet/AspNetKatana/issues/54)? This issue isn't directly connected to SignalR, SignalR is just what's triggering it in your scenario.

I'm closing this issue to clarify that the issue does not appear to be in SignalR. Feel free to comment further if you have questions and we can always re-open the issue if there's something SignalR can fix here.
