### ISSUE TITLE
HubProxy is not threadsafe when defining a State just before Invoking a method

### ISSUE THREAD

**Issue by alisovoy** [SignalR/SignalR#4319]
before invoking a method I set a State:

![image](https://user-images.githubusercontent.com/22320084/53515187-b7eb4f00-3ac9-11e9-8403-7e32dd24b415.png)

and this piece of code is executed multiple times concurrently
### Expected  behavior
Works flawlessly
### Actual behavior
throws exception:

> at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.AspNet.SignalR.Client.ConnectionExtensions.JsonSerializeObject(IConnection connection, Object value) in /_/src/Microsoft.AspNet.SignalR.Client/ConnectionExtensions.cs:line 53
   at Microsoft.AspNet.SignalR.Client.Hubs.HubProxy.Invoke[TResult,TProgress](String method, Action`1 onProgress, Object[] args) in /_/src/Microsoft.AspNet.SignalR.Client/Hubs/HubProxy.cs:line 174
   at Microsoft.AspNet.SignalR.Client.Hubs.HubProxy.Invoke[T](String method, Object[] args) in src/Microsoft.AspNet.SignalR.Client/Hubs/HubProxy.cs:line 76
**Result Message: System.InvalidOperationException : Collection was modified; enumeration operation may not execute.**

### Steps to reproduce
![image](https://user-images.githubusercontent.com/22320084/53515690-eb7aa900-3aca-11e9-97c8-344a5c3f6415.png)

### Additional information:
In HubProxy the State is supposed to be threadsafe. Otherwise why would you put locks here:
![image](https://user-images.githubusercontent.com/22320084/53516036-9f7c3400-3acb-11e9-9148-381b06897079.png)

But in invoke method you want to serialize the state(which involves enumeration of the dictionary) without a lock:

![image](https://user-images.githubusercontent.com/22320084/53516176-f7b33600-3acb-11e9-9e2a-59abbcda2545.png)

that gives "Collection was modified; enumeration operation may not execute." exception in a highly concurrent environment.
Please, fix it.

the solution could be to add an extra lock around serialization, or remove all locks and use the ConcurrentDictionary OR your best elegant solution

thanks!

**Comment by halter73** [comment]
FYI, for a while now, we've been encouraging developers not to use SignalR hub state feature. As [this guide](https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server#how-to-pass-state-between-clients-and-the-hub-class) notes, it's very inefficient for sending large amounts of data.

It's also somewhat unintuitive *when* state gets synchronized. As I'm sure you've notice just, setting the state object doesn't force a sync, as subsequent message has to be sent.

I highly recommend manually synchronizing state using hub method/callback parameters and return values instead. That being said, we'll add the lock around `_state.Count` for 2.4.1.

**Comment by halter73** [comment]
Another thing I'll note, is if the data structures you put inside of the hubproxy state dictionary are modified from other threads, you'll still have thread safety issues. No amount of internal locking in the SignalR client will save you from that.

**Comment by alisovoy** [comment]
thank you for your reply
> Another thing I'll note, is if the data structures you put inside of the hubproxy state dictionary are modified from other threads, you'll still have thread safety issues. No amount of internal locking in the SignalR client will save you from that.

indeed, I realized that just after submitting the issue. I've stopped using the state in this way and pass the data as an extra parameter.  

> I highly recommend manually synchronizing state using hub method/callback parameters and return values instead. That being said, we'll add the lock around _state.Count for 2.4.1.

The problem happens while serializing the hubData (line 174 on the screenshot) having the reference to state, not when calling the count property that does not enumerate.

**Comment by anurse** [comment]
This is fixed in version [2.4.1](https://github.com/SignalR/SignalR/releases/tag/2.4.1) which is now released to NuGet.org and NPM.
