### ISSUE TITLE
NullReferenceException in LostConnection

### ISSUE THREAD

**Issue by zhuweid** [SignalR/SignalR#4423]
after upgrading from Microsoft.AspNet.SignalR.Client.2.2.0 to Microsoft.AspNet.SignalR.Client.2.2.1, our application had a few crashes with the stack trace below.

It all works fine in version 2.2.0, it seems the changes in HeartbeatMonitor.CheckKeepAlive() has caused this issue, can you please take a look?

Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.AspNet.SignalR.Client.Transports.AutoTransport.LostConnection(Microsoft.AspNet.SignalR.Client.IConnection)
   at Microsoft.AspNet.SignalR.Client.HeartbeatMonitor.CheckKeepAlive(System.TimeSpan)
   at Microsoft.AspNet.SignalR.Client.HeartbeatMonitor.Beat()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by zhuweid** [comment]
there is another crash with different stacktrace

Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.AspNet.SignalR.Client.Connection.Stop(System.TimeSpan)
   at Microsoft.AspNet.SignalR.Client.Connection.Stop(System.Exception)
   at Microsoft.AspNet.SignalR.Client.Transports.TransportHelper.VerifyLastActive(Microsoft.AspNet.SignalR.Client.IConnection)
   at Microsoft.AspNet.SignalR.Client.Transports.WebSocketTransport+<DoReconnect>d__24.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by anurse** [comment]
For the first one, there was an additional call to `LostConnection` added in 2.4.1 but that shouldn't be affecting 2.2.1. As far as I can tell there were no changes to this code between 2.2.0 and 2.2.1.

Do you have any way to reproduce this exception?

> there is another crash with different stacktrace

This is a client stack trace. Your first stack trace was on the server. These are almost certainly different issues and you should file a separate bug for the client one.

**Comment by BrennanConroy** [comment]
The second trace looks exactly like https://github.com/SignalR/SignalR/issues/4403

**Comment by anurse** [comment]
Good eye :). Yeah, so let's use #4403 to track that work. @zhuweid please let me know if you have any more information on how to repro the first exception. It may also be useful to [enable server-side tracing](https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing#enabling-tracing-on-the-server) and see if there are any useful logs there.

**Comment by zhuweid** [comment]
@anurse , for the first issue, we have never seen this issue in our development environment, it was reported by one of our custom in their azure environment several days ago, and that issue only occurred once so far and could not be reproduced. we asked the client to monitor and let us know if that issue happened again.

as for the second issue, is there any plan  to fix it in the next release? when do you think that can be fixed? as we plan for a patch for our customers by upgrading signalR client library to the latest version.

one general question is: would it be possible to catch this kind of unhanded exception in our background monitoring threads/events, and fire the onerror event instead of crashing the application? we use the signalR client library in our windows service, and we want our service continue running even there is any error from signalR.

**Comment by BrennanConroy** [comment]
Closing in favor of https://github.com/SignalR/SignalR/issues/4403
