### ISSUE TITLE
Intermittent AccessViolationExceptions being raised

### ISSUE THREAD

**Issue by adhowlett81** [SignalR/SignalR#4450]
Using SignalR v2.4.0 on .Net Framework v4.7.1 I'm receiving an intermittent System.AccessViolation exception.  The exception detail is as follows:

```
Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at System.Web.Hosting.UnsafeIISMethods.MgdExplicitFlush(IntPtr, Boolean, Boolean ByRef)
   at System.Web.Hosting.IIS7WorkerRequest.ExplicitFlush()
   at System.Web.HttpResponse.Flush(Boolean, Boolean)
   at System.Web.HttpWriter.WriteFromStream(Byte[], Int32, Int32)
   at Microsoft.Owin.Host.SystemWeb.CallStreams.OutputStream.Write(Byte[], Int32, Int32)
   at Microsoft.AspNet.SignalR.Owin.ServerResponse.Write(System.ArraySegment`1<Byte>)
   at Microsoft.AspNet.SignalR.Transports.LongPollingTransport.PerformPartialSend(System.Object)
   at Microsoft.AspNet.SignalR.Infrastructure.TaskQueue.InvokeNext(System.Func`2<System.Object,System.Threading.Tasks.Task>, System.Object)
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.FromMethod[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`4<System.__Canon,System.__Canon,System.__Canon,System.Threading.Tasks.Task>, System.__Canon, System.__Canon, System.__Canon)
   at Microsoft.AspNet.SignalR.Infrastructure.TaskQueue.Enqueue(System.Func`2<System.Object,System.Threading.Tasks.Task>, System.Object)
   at Microsoft.AspNet.SignalR.Transports.TransportDisconnectBase.EnqueueOperation(System.Func`2<System.Object,System.Threading.Tasks.Task>, System.Object)
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.FromMethod[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`3<System.__Canon,System.__Canon,System.Threading.Tasks.Task>, System.__Canon, System.__Canon)
   at Microsoft.AspNet.SignalR.Transports.LongPollingTransport.OnMessageReceived(Microsoft.AspNet.SignalR.Transports.PersistentResponse)
   at Microsoft.AspNet.SignalR.Infrastructure.Connection+<>c.<Receive>b__43_0(Microsoft.AspNet.SignalR.Messaging.MessageResult, System.Object)
   at Microsoft.AspNet.SignalR.Messaging.Subscription+<Invoke>d__25.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.AspNet.SignalR.Messaging.Subscription+<Invoke>d__25, Microsoft.AspNet.SignalR.Core, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<Invoke>d__25 ByRef)
   at Microsoft.AspNet.SignalR.Messaging.Subscription.Invoke(Microsoft.AspNet.SignalR.Messaging.MessageResult, System.Action`2<Microsoft.AspNet.SignalR.Messaging.Subscription,System.Object>, System.Object)
   at Microsoft.AspNet.SignalR.Messaging.Subscription+<Work>d__26.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.AspNet.SignalR.Messaging.Subscription+<Work>d__26, Microsoft.AspNet.SignalR.Core, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<Work>d__26 ByRef)
   at Microsoft.AspNet.SignalR.Messaging.Subscription.Work()
   at Microsoft.AspNet.SignalR.Messaging.MessageBroker+<DoWork>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.AspNet.SignalR.Messaging.MessageBroker+<DoWork>d__9, Microsoft.AspNet.SignalR.Core, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<DoWork>d__9 ByRef)
   at Microsoft.AspNet.SignalR.Messaging.MessageBroker.DoWork(WorkContext)
   at Microsoft.AspNet.SignalR.Messaging.MessageBroker+<>c+<<ScheduleWork>g__Worker|8_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[[Microsoft.AspNet.SignalR.Messaging.MessageBroker+<>c+<<ScheduleWork>g__Worker|8_0>d, Microsoft.AspNet.SignalR.Core, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<<ScheduleWork>g__Worker|8_0>d ByRef)
   at Microsoft.AspNet.SignalR.Messaging.MessageBroker+<>c.<ScheduleWork>g__Worker|8_0(System.Object)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

The application is being used 24 hours a day, 7 days a week with approximately 50-100 active connections at any one time.  SignalR messages sent from the server are all done via groups rather than individual connection Ids.  The exception itself only occurs between 
2 to 4 times in any particular day and when it does it will cause the IIS process (w3wp.exe) to recycle.  I also notice that the exception appears to indicate that it has been generated from a Long Polling process (Microsoft.AspNet.SignalR.Transports.LongPollingTransport.PerformPartialSend(System.Object)) so I'm wondering if it's being caused by a specific client browser connection?

I've attached an associated Windows Error Reporting file in case this is of any help.
[Report.txt](https://github.com/SignalR/SignalR/files/4303393/Report.txt)

**Comment by davidfowl** [comment]
The bug is likely a race between the http request ending and a pending flush being executing afterwards. Seems like something we should fix 

cc @halter73

**Comment by halter73** [comment]
The LongPollingTransport is designed so that the TaskQueue should drain before we complete the request on our side. I don't see any obvious bugs in that logic. Even if that logic is buggy, accessing the request after it completes shouldn't AV. That would be a bug in IIS, not SignalR.

Unless there's an uptick in reports of this kind of failure, we don't plan to investigate this further.

> IMPORTANT: There will be no new features added to this product. We are in maintenance mode and only fixing critical issues.

https://github.com/SignalR/SignalR#aspnet-signalr
