### ISSUE TITLE
System.Threading.Tasks.Task.ThrowIfExceptional when called connection.Start().Wait()

### ISSUE THREAD

**Issue by Suresh9sb** [SignalR/SignalR#4498]
Hi Team,
We are using Asp.net SignalR v 2.4.1 and we have .Net client WPF which connects to hub and talks back and forth. 
we have some memory issues so we are testing with load when we start load we see below errors being triggered when we call  
			connection.Start().Wait() from the load app. 

public override async Task OnConnected() 
  - we collect user data from Context.User.Indentity.Name 
  - save the User details in the system with connection id 

we are testing a server method which sends data to particular client with NTLogin.

=====Error in CreateConnection=====
=====Error in CreateConnection=====
One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at xxx.SignalR.LoadSimulator.SignalRHubConnection.Initialize() in C:\Users\xxx999\Desktop\SignalR Load Testing\signalr-load-simulator-master\signalr-load-simulator-master\xxx.SignalR.LoadSimulator\SignalRConnection.cs:line 89
   at xxx.SignalR.LoadSimulator.SignalRHubConnection..ctor(ConnectionManager instance, String url, String hubName) in C:\Users\xxx999\Desktop\SignalR Load Testing\signalr-load-simulator-master\signalr-load-simulator-master\xxx.SignalR.LoadSimulator\SignalRConnection.cs:line 26
   at xxx.SignalR.LoadSimulator.ConnectionManager.<CreateConnections>b__20_0(Int32 i) in C:\Users\xxx999\Desktop\SignalR Load Testing\signalr-load-simulator-master\signalr-load-simulator-master\xxx.SignalR.LoadSimulator\ConnectionManager.cs:line 186
One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at xxx.SignalR.LoadSimulator.SignalRHubConnection.Initialize() in C:\Users\xxx999\Desktop\SignalR Load Testing\signalr-load-simulator-master\signalr-load-simulator-master\xxx.SignalR.LoadSimulator\SignalRConnection.cs:line 89
   at xxx.SignalR.LoadSimulator.SignalRHubConnection..ctor(ConnectionManager instance, String url, String hubName) in C:\Users\xxx999\Desktop\SignalR Load Testing\signalr-load-simulator-master\signalr-load-simulator-master\xxx.SignalR.LoadSimulator\SignalRConnection.cs:line 26
   at xxx.SignalR.LoadSimulator.ConnectionManager.<CreateConnections>b__20_0(Int32 i) in C:\Users\xxx999\Desktop\SignalR Load Testing\signalr-load-simulator-master\signalr-load-simulator-master\xxx.SignalR.LoadSimulator\ConnectionManager.cs:line 186
Transport timed out trying to connect

One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at xxx.SignalR.LoadSimulator.SignalRHubConnection.Initialize() in C:\Users\xxx999\Desktop\SignalR Load Testing\signalr-load-simulator-master\signalr-load-simulator-master\xxx.SignalR.LoadSimulator\SignalRConnection.cs:line 89
   at xxx.SignalR.LoadSimulator.SignalRHubConnection..ctor(ConnectionManager instance, String url, String hubName) in C:\Users\xxx999\Desktop\SignalR Load Testing\signalr-load-simulator-master\signalr-load-simulator-master\xxx.SignalR.LoadSimulator\SignalRConnection.cs:line 26
   at xxx.SignalR.LoadSimulator.ConnectionManager.<CreateConnections>b__20_0(Int32 i) in C:\Users\xxx999\Desktop\SignalR Load Testing\signalr-load-simulator-master\signalr-load-simulator-master\xxx.SignalR.LoadSimulator\ConnectionManager.cs:line 186
One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at xxx.SignalR.LoadSimulator.SignalRHubConnection.Initialize() in C:\Users\xxx999\Desktop\SignalR Load Testing\signalr-load-simulator-master\signalr-load-simulator-master\xxx.SignalR.LoadSimulator\SignalRConnection.cs:line 89
   at xxx.SignalR.LoadSimulator.SignalRHubConnection..ctor(ConnectionManager instance, String url, String hubName) in C:\Users\xxx999\Desktop\SignalR Load Testing\signalr-load-simulator-master\signalr-load-simulator-master\xxx.SignalR.LoadSimulator\SignalRConnection.cs:line 26
   at xxx.SignalR.LoadSimulator.ConnectionManager.<CreateConnections>b__20_0(Int32 i) in C:\Users\xxx999\Desktop\SignalR Load Testing\signalr-load-simulator-master\signalr-load-simulator-master\xxx.SignalR.LoadSimulator\ConnectionManager.cs:line 186
Transport timed out trying to connect

One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at xxx.SignalR.LoadSimulator.SignalRHubConnection.Initialize() in C:\Users\xxx999\Desktop\SignalR Load Testing\signalr-load-simulator-master\signalr-load-simulator-master\xxx.SignalR.LoadSimulator\SignalRConnection.cs:line 89
   at xxx.SignalR.LoadSimulator.SignalRHubConnection..ctor(ConnectionManager instance, String url, String hubName) in C:\Users\xxx999\Desktop\SignalR Load Testing\signalr-load-simulator-master\signalr-load-simulator-master\xxx.SignalR.LoadSimulator\SignalRConnection.cs:line 26
   at xxx.SignalR.LoadSimulator.ConnectionManager.<CreateConnections>b__20_0(Int32 i) in C:\Users\xxx999\Desktop\SignalR Load Testing\signalr-load-simulator-master\signalr-load-simulator-master\xxx.SignalR.LoadSimulator\ConnectionManager.cs:line 186
One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at xxx.SignalR.LoadSimulator.SignalRHubConnection.Initialize() in C:\Users\xxx999\Desktop\SignalR Load Testing\signalr-load-simulator-master\signalr-load-simulator-master\xxx.SignalR.LoadSimulator\SignalRConnection.cs:line 89
   at xxx.SignalR.LoadSimulator.SignalRHubConnection..ctor(ConnectionManager instance, String url, String hubName) in C:\Users\xxx999\Desktop\SignalR Load Testing\signalr-load-simulator-master\signalr-load-simulator-master\xxx.SignalR.LoadSimulator\SignalRConnection.cs:line 26
   at xxx.SignalR.LoadSimulator.ConnectionManager.<CreateConnections>b__20_0(Int32 i) in C:\Users\xxx999\Desktop\SignalR Load Testing\signalr-load-simulator-master\signalr-load-simulator-master\xxx.SignalR.LoadSimulator\ConnectionManager.cs:line 186
Transport timed out trying to connect

Transport timed out trying to connect

Transport timed out trying to connect

Transport timed out trying to connect

Transport timed out trying to connect

**Comment by halter73** [comment]
If OnConnectedAsync is taking long, you can try increasing HubConnection.TransportConnectTimeout to something more than zero. This increases the overall transport timeout to give OnConnectedAsync more time to finish without failing with the TimeoutException. You could also move the initialization logic to another hub method that doesn't have default timeouts. In the future this kind of question would be better asked on stackoverflow.com.
