### ISSUE TITLE
Android StackOverFlow

### ISSUE THREAD

**Issue by nts0311** [SignalR/SignalR#4523]
I Have an app that use SignalR Java client version 5.0.1. The app is intended to run for long time, almost 24/7. 
In the app the SignalR is used for receiving command from server and it will ping server every 15s. 

### Expected  behavior
The app must run all day, all night, 24/7
### Actual behavior
The app crash after about a day of running.
### Steps to reproduce

Stacktrace:

[log.txt](https://github.com/SignalR/SignalR/files/5842673/log.txt)

```
2021.01.19 at 22:33:08

Thread name: OkHttp Dispatcher
Message: stack size 1037KB
Cause: null
Stack trace: 
java.lang.StackOverflowError: stack size 1037KB
at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onError(SingleFlatMapCompletable.java:97)
	at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.onError(CompletableConcatArray.java:60)
...
at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onError(SingleFlatMapCompletable.java:97)
	at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.onError(CompletableConcatArray.java:60)
	at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onError(SingleFlatMapCompletable.java:97)
	at io.reactivex.subjects.SingleSubject.onError(SingleSubject.java:153)
	at com.microsoft.signalr.DefaultHttpClient$2.onFailure(DefaultHttpClient.java:149)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:180)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by BrennanConroy** [comment]
This issue belongs in the github.com/dotnet/aspnetcore. Can you provide any info about what you are doing in your app when you file the issue there?

**Comment by nts0311** [comment]
@BrennanConroy the app is a media client and is used in restaurants to present video, image, audio ... . It used SignalR to receive command to download media file, control audio, scheduled media play time,... . And it will ping to server every 15s to check the connection.
I will open a issue at github.com/dotnet/aspnetcore
