### ISSUE TITLE
Not able to specify client id of managed identity

### ISSUE THREAD

**Issue by mnirck** [SignalR/SignalR#4535]
The set-up is as followed :

We have an AKS cluster and a Signal-R resource configured in our environment. We have several micro services within the AKS cluster that need to contact Azure Resources outside the AKS Cluster.
For authentication we use the aad-pod-identity for using managed identities in the Azure Active Directory. For each resource that we connect from the AKS Cluster to a Azure Resource we create a Managed Identity. So per Azure Resource we have a managed identity, so this means that a pod within AKS Cluster from the application can have several managed identities for authenticating to an Azure Resource. This means that we have A managed identity per Azure Resource and not a managed identity per pod in the AKS cluster.
In all cases we want to contact a Azure Resource we can specify the client id from the managed identity for using the correct identity for connecting to the Azure Resource, except the Signal-R resource we can not specify the managed identity so when you have multiple managed identities that you can use in a pod, he will choose at round robin witch identity he will use.
The keys are apparently stored in an array and it’s not always sorted the same way. It seems like Signal-R is expecting a Service Principal with a secret instead of a Managed Identity.

An example :
Request 1
Key 1 – Key Vault
Key 2 – Storage Account
Key 3 – Signal R
Request 2
Key 1 – Signal R
Key 2 – Key Vault
Key 3 – Storage Account
Request 3
Key 1 – Signal R
Key 2 – Key Vault
key 3 – Storage Account
Request 4 ……

Is there a way to use the managed identiy client id for the connection string that we create to Signal R from a pod in the AKS Cluster from the application?

Describe the bug
Endpoint=https://sr-tst-nmtm-01.service.signalr.net;AuthType=aad;clientId=****;tenantId=******
System.ArgumentException: Connection string missing required properties clientSecret or clientCert. (Parameter 'clientSecret')

Error Message
2021-02-10T07:55:54.987469189Z [07:55:54 FTL] Application startup exception
2021-02-10T07:55:54.987505888Z System.ArgumentException: Connection string missing required properties clientSecret or clientCert. (Parameter 'clientSecret')
2021-02-10T07:55:54.987511688Z    at Microsoft.Azure.SignalR.ConnectionStringParser.BuildAadAccessKey(Dictionary2 dict, String endpoint, Nullable1 port)
2021-02-10T07:55:54.987515388Z    at Microsoft.Azure.SignalR.ConnectionStringParser.Parse(String connectionString)
2021-02-10T07:55:54.987518888Z    at Microsoft.Azure.SignalR.ServiceEndpoint..ctor(String connectionString, EndpointType type, String name)
2021-02-10T07:55:54.987522488Z    at Microsoft.Azure.SignalR.Common.Endpoints.IServiceEndpointOptionExtensions.GetMergedEndpoints(IServiceEndpointOptions options)+MoveNext()
2021-02-10T07:55:54.987526288Z    at System.Linq.Enumerable.DistinctIterator1.MoveNext() 2021-02-10T07:55:54.987529688Z    at System.Linq.Lookup2.Create(IEnumerable1 source, Func2 keySelector, IEqualityComparer1 comparer) 2021-02-10T07:55:54.987533188Z    at System.Linq.GroupedEnumerable2.GetEnumerator()
2021-02-10T07:55:54.987536488Z    at System.Linq.Enumerable.SelectEnumerableIterator2.MoveNext() 2021-02-10T07:55:54.987539688Z    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable1 source, Func2 keySelector, Func2 elementSelector, IEqualityComparer1 comparer) 2021-02-10T07:55:54.987542888Z    at Microsoft.Azure.SignalR.ServiceEndpointManagerBase.GetValuableEndpoints(IEnumerable1 endpoints)
2021-02-10T07:55:54.987546388Z    at Microsoft.Azure.SignalR.ServiceEndpointManagerBase..ctor(IEnumerable1 endpoints, ILogger logger) 2021-02-10T07:55:54.987549488Z    at Microsoft.Azure.SignalR.ServiceEndpointManagerBase..ctor(IServiceEndpointOptions options, ILogger logger) 2021-02-10T07:55:54.987552788Z    at Microsoft.Azure.SignalR.ServiceEndpointManager..ctor(IServerNameProvider provider, IOptionsMonitor1 optionsMonitor, ILoggerFactory loggerFactory)
2021-02-10T07:55:54.987555988Z    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
2021-02-10T07:55:54.987559388Z    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2021-02-10T07:55:54.987562488Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2021-02-10T07:55:54.987579988Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument) 2021-02-10T07:55:54.987583988Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType) 2021-02-10T07:55:54.987587688Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context) 2021-02-10T07:55:54.987590888Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2021-02-10T07:55:54.987594188Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2021-02-10T07:55:54.987597688Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument) 2021-02-10T07:55:54.987601088Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType) 2021-02-10T07:55:54.987604388Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context) 2021-02-10T07:55:54.987607688Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2021-02-10T07:55:54.987610888Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
2021-02-10T07:55:54.987614188Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.b__0(ServiceProviderEngineScope scope)
2021-02-10T07:55:54.987618088Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
2021-02-10T07:55:54.987621588Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
2021-02-10T07:55:54.987624888Z    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2021-02-10T07:55:54.987628088Z    at Microsoft.Azure.SignalR.ServiceHubDispatcher.Start(Endpoint endpoint, Type hubType, ConnectionDelegate app)
2021-02-10T07:55:54.987631288Z    at Microsoft.Azure.SignalR.AzureSignalRHostedService.Start()
2021-02-10T07:55:54.987634388Z    at Microsoft.Azure.SignalR.AzureSignalRStartupFilter.<>c__DisplayClass0_0.b__0(IApplicationBuilder app)
2021-02-10T07:55:54.987637888Z    at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.b__0(IApplicationBuilder app)
2021-02-10T07:55:54.987644588Z    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
2021-02-10T07:55:55.081933869Z [07:55:55 FTL] Host terminated unexpectedly

Steps To Reproduce
1 pod with multiple managed identities
Use 1 managed identity to connect to Signal-R resource

Expected behavior
That you can specify a client id of the Managed Identity in the connection string

**Comment by mnirck** [comment]
Sorry my mistake

**Comment by BrennanConroy** [comment]
Looks like an issue for the https://github.com/Azure/azure-signalr repo?
