### ISSUE TITLE
Adding to a group terminates connection after 1-2 min

### ISSUE THREAD

**Issue by xhaaix** [SignalR/SignalR#4549]
version of SignalR packages is 2.4.1
server is WebAPI, .NET 4.5
client is WPF, .NET 4.7.2
scale-out plan is Redis

when I tried to use groups functionality of SignalR I was getting System.InvalidOperationException: 'The operation was canceled.'
**server code:**
```
public Task AddToGroup(string groupName)
{
            return Groups.Add(Context.ConnectionId, groupName);
 }
```
**client code:**

```
await _hubConnection.Start();
await _hubProxy.Invoke("AddToGroup", "WorkItem");
```

**some logs:**

```
SignalR.Transports.TransportHeartBeat Information: 0 : Connection d9d8fa87-557a-4152-b1ba-2a882a6116e0 is New.

SignalR.ScaleoutMessageBus Information: 0 : OnReceived(0, 19141, 1)
SignalR.ScaleoutMessageBus Verbose: 0 : Received message 19141: '{"WaitForAck":true,"Id":"7b71c51e-a6b5-4df1-a22c-27b2f1102806","CommandType":"AddToGroup","Value":"hg-ItemChangedNotifierHub.WorkItem"}' over ScaleoutMessageBus

SignalR.Transports.WebSocketTransport Verbose: 0 : Sending outgoing message. Connection id: d9d8fa87-557a-4152-b1ba-2a882a6116e0, transport: WebSocketTransport, message: {"C":"s-0,4AC5","G":"PruCEMeZXDIoWyIMA4UCDEPaErgwaQRNN9G4D/y9dGLEIv1C1sxbmSkg9ZXs42PDtUutNCLfUbxcfBwFc1GXvm4wouA/+goS1lFuhmfYZIv37yYbbBD4pigThQvQjd3CJlOdrWYSjj7GgtaBMVrHPby8pZ6r0xf/t/n7y/uKWEw=","M":[]}

SignalR.Transports.TransportHeartBeat Verbose: 0 : KeepAlive(d9d8fa87-557a-4152-b1ba-2a882a6116e0)

Exception thrown: 'StackExchange.Redis.RedisTimeoutException' in StackExchange.Redis.StrongName.dll
Exception thrown: 'StackExchange.Redis.RedisConnectionException' in StackExchange.Redis.StrongName.dll

SignalR.HubDispatcher Verbose: 0 : Sending hub invocation result to connection d9d8fa87-557a-4152-b1ba-2a882a6116e0 using transport WebSocketTransport
SignalR.Transports.WebSocketTransport Verbose: 0 : Sending outgoing message. Connection id: d9d8fa87-557a-4152-b1ba-2a882a6116e0, transport: WebSocketTransport, message: {"I":"0","E":"The operation was canceled."}

SignalR.Transports.WebSocketTransport Error: 0 : OnError(d9d8fa87-557a-4152-b1ba-2a882a6116e0, System.Net.WebSockets.WebSocketException (0x800703E3): The I/O operation has been aborted because of either a thread exit or an application request
   at System.Web.WebSockets.WebSocketPipe.<>c__DisplayClass9_0.<ReadFragmentAsync>b__0(Int32 hrError, Int32 cbIO, Boolean fUtf8Encoded, Boolean fFinalFragment, Boolean fClose)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.WebSockets.AspNetWebSocket.<DoWork>d__45`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.WebSockets.AspNetWebSocket.<>c__DisplayClass36_0.<<ReceiveAsyncImpl>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.WebSockets.WebSocketMessageReader.<ReadMessageAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.WebSockets.WebSocketHandler.<ProcessWebSocketRequestAsync>d__25.MoveNext())
SignalR.Transports.WebSocketTransport Information: 0 : CloseSocket(d9d8fa87-557a-4152-b1ba-2a882a6116e0)

SignalR.Transports.WebSocketTransport Information: 0 : Abort(d9d8fa87-557a-4152-b1ba-2a882a6116e0)
SignalR.Transports.TransportHeartBeat Information: 0 : Removing connection d9d8fa87-557a-4152-b1ba-2a882a6116e0
SignalR.Transports.WebSocketTransport Information: 0 : End(d9d8fa87-557a-4152-b1ba-2a882a6116e0)

SignalR.MessageBus Information: 0 : RemoveTopic(hc-ItemChangedNotifierHub.d9d8fa87-557a-4152-b1ba-2a882a6116e0)
SignalR.MessageBus Information: 0 : RemoveTopic(c-d9d8fa87-557a-4152-b1ba-2a882a6116e0)
SignalR.MessageBus Information: 0 : RemoveTopic(hg-ItemChangedNotifierHub.WorkItem)
```
SingalR is working here for about 2 years with Redis scale-out. The issue only occurred when I tried to add some groups.
Also sometimes I got System.InvalidOperationException: 'Connection was disconnected before invocation result was received.' instead 

Any advice please?
Is this possible I misuse this functionality somehow?

Thank you!

**Comment by BrennanConroy** [comment]
Looks like you're hitting a redis exception
>Exception thrown: 'StackExchange.Redis.RedisTimeoutException' in StackExchange.Redis.StrongName.dll
Exception thrown: 'StackExchange.Redis.RedisConnectionException' in StackExchange.Redis.StrongName.dll

Is your redis server up and accessible from the app?

**Comment by xhaaix** [comment]
yep, the app uses this server for more then 2 years now without any issues (well in fact I do recall several outages along the way :)) but it stopped working with signalR groups. Same setup worked fine with ServiceBus scale out plan. Now we abandon the idea to use groups and use topics instead (with the same Redis)
