### ISSUE TITLE
SignalR Communication with React Issues

### ISSUE THREAD

**Issue by vikassharma5981** [SignalR/SignalR#4636]
We are using SignalR for some notifications to the react client, React client is using @microsoftsignalr latest version.
SignalR version 1.1.0
While communicating with a net core client on some machines it is working as expected but not on some machines.
While communicating with React client it only works with LongPolling(set explicitly).
Unsure about how we narrow down the root cause here.
**Trace:**
```
**      Request finished HTTP/1.1 POST http://XXXXX/notificationsHub/negotiate?negotiateVersion=1 text/plain;charset=UTF-8 0 - 200 316 application/json 185.2137ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://XXXXX/notificationsHub?id=NC5foN-f_OxNQmOR9D92gA&access_token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkV4dHJvbkFkbWluMjAxOSIsImFjdG9ydCI6IjEiLCJuYmYiOjE2NTc3Njg2MTksImV4cCI6MTY1Nzc3NTgxOSwiaWF0IjoxNjU3NzY4NjE5LCJhdWQiOiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCAxMC4wOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTAzLjAuMC4wIFNhZmFyaS81MzcuMzYifQ.QVBM5WQxvWfzzjWZqqAajR6CMWTboNWWIYLHEpjNABkwxTGzZu0kPTZH1bjeLZGUJ41uREkVwSiazk8IOpl55w - -
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
      CORS policy execution successful.
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
      Successfully validated the token.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'notificationsHub'
dbug: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher[4]
      Establishing new connection.
dbug: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[1]
      Socket opened using Sub-Protocol: '(null)'.
dbug: Microsoft.AspNetCore.SignalR.HubConnectionHandler[5]
      OnConnectedAsync started.
dbug: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[14]
      Socket connection closed prematurely.
      System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
         at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
         at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
         at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
         at Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsServerTransport.StartReceiving(WebSocket socket)
dbug: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[4]
      Waiting for the application to finish sending data.
dbug: Microsoft.AspNetCore.SignalR.HubConnectionContext[5]
      Failed connection handshake.**
```
****   
Dot Net Core client snippet
```
`  var connection = new signalR.HubConnectionBuilder()
            .withUrl("http://xxx/notificationsHub",
            {
                accessTokenFactory: () => connectionToken,
            
            }
        ).configureLogging(signalR.LogLevel.Trace)
            .build();`
```

**React Snippet**
```
`var connection = new signalR.HubConnectionBuilder()
    .withUrl("http://xxx/notificationsHub", {
      accessTokenFactory() {
        return "xxxxx";
      },
   })
    .build();
`
```

Any help here would be highly appreciated.

**Comment by JGdalevich** [comment]
This repo is for SignalR for .NET Framework.

For SignalR .NET Core, use:  https://docs.microsoft.com/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-6.0&tabs=visual-studio

**Comment by BrennanConroy** [comment]
Wrong repo, and no activity, closing.
